Ayush7614/Daily-Coding-DS-ALGO-Practice

Hackerank/Print element in Linked List.c
=> Create Print element in Linked List.c

Gfg/power_of_2.cpp
I have written a program to check whether the number is a power of 2 or not using bit manipulation.
=> Program to check wether number is a power of 2 or not

Hackerank/The Minion Game.py
=> Create The Minion Game.py

Hackerank/Sorting Array of Strings.c
=> Create Sorting Array of Strings.c

Hackerank/Printing Tokens.c
=> Create Printing Tokens.c

Hackerank/Array Reversal.c
=> Create Array Reversal.c

Hackerank/Permutations of Strings.c
=> Create Permutations of Strings.c

Hackerank/Post Transition.c
=> Create Post Transition.c

Hackerank/Variadic functions in C.c
=> Create Variadic functions in C.c

Hackerank/Querying the Document.c
=> Create Querying the Document.c

Codechef/Chef and Groups.py, Codechef/Interesting XOR.cpp, Codechef/No Time To Wait.py, Codechef/Nobel.py, Codechef/Oliver.cpp, Codechef/Possible Victory.py, Codechef/Team Name.py
I have added some Codechef Problem Solution.
=> Codechef Solutions Added

Hackerank/Words Score.py
=> Create Words Score.py

Hackerank/Structuring the Document.c
=> Create Structuring the Document.c

Hackerank/Time conversion.c
=> Create Time conversion.c

Hackerank/Even Fibonacci numbers.c, Hackerank/Largest palindrome product.c, Hackerank/Largest prime factor.cpp, Hackerank/Multiples of 3 and 5.c, Hackerank/Smallest multiple.cpp
Adding the solution for the Project Euler Problem 1, 2, 3, 4 and 5.
Fixes #8 #9
=> Adding solutions for Project Euler Problems (HackerRank)

Hackerank/10001st prime.cpp, Hackerank/Largest product in a series.py, Hackerank/Special Pythagorean triplet.py, Hackerank/Sum square difference.cpp, Hackerank/Summation of primes.cpp
Adding the solution for the Project Euler Problem 6, 7, 8, 9 and 10.
Fixes #8 #9
=> Adding solutions for Project Euler Problems 06 to 10 (HackerRank)

Hackerank/Highly divisible triangular number.cpp, Hackerank/Large sum.py, Hackerank/Largest product in a grid.cpp, Hackerank/Lattice paths.cpp, Hackerank/Longest Collatz sequence.cpp
Adding the solution for the Project Euler Problem 11, 12, 13, 14 and 15.
Fixes #8 #9
=> Adding solutions for Project Euler Problems 11 to 15 (HackerRank)

README.md
Changed the branch referenced in git pull command from master to main(in README.md). 
Fixes #60
=> Change branch referenced from master to main (in README.md)

Hackerank/Small Triangles, Large Triangles.c
=> Create Small Triangles, Large Triangles.c

Hackerank/Counting Sundays.cpp, Hackerank/Factorial digit sum.py, Hackerank/Maximum path sum I.cpp, Hackerank/Number to Words.c, Hackerank/Power digit sum.py
Adding the solution for the Project Euler Problem 16, 17, 18, 19 and 20.
Fixes #8 #9
=> Adding solutions for Project Euler Problems 16 to 20 (HackerRank)

Hackerank/Funny String.c
=> Create Funny String.c

Hackerank/Sales by Match.c
=> Create Sales by Match.c

Hackerank/Weighted Mean.py
=> Create Weighted Mean.py

Hackerank/Printing Pattern Using Loops.c
=> Create Printing Pattern Using Loops.c

Hackerank/Interquartile Range.py, Hackerank/Standard Deviation.py
=> Create Interquartile Range.py

Hackerank/Geometric Distribution 2.cpp
=> Create Geometric Distribution 2.cpp

Hackerank/Geometric Distribution 1.cpp
=> Create Geometric Distribution 1.cpp

Hackerank/Binomial Distribution 2.cpp
=> Create Binomial Distribution 2.cpp

Hackerank/Binomial Distribution 1.py
=> Create Binomial Distribution 1.py

Hackerank/Digit Frequency.c
=> Create Digit Frequency.c

Hackerank/Normal Distribution 2.cpp
=> Create Normal Distribution 2.cpp

Hackerank/Normal Distribution 1.cpp
=> Create Normal Distribution 1.cpp

Hackerank/Poisson Distribution.cpp
=> Create Poisson Distribution.cpp

Hackerank/Poisson Distribution 2.cpp
=> Create Poisson Distribution 2.cpp

Hackerank/Spearman's Rank Correlation.cpp
=> Create Spearman's Rank Correlation.cpp

Hackerank/Dynamic Array in C.c
=> Create Dynamic Array in C.c

Hackerank/Pearson Correlation Coefficient.cpp
=> Create Pearson Correlation Coefficient.cpp

Hackerank/The Central Limit Theorem.cpp
=> Create The Central Limit Theorem.cpp

Hackerank/The Central Limit Theorem 2.cpp
=> Create The Central Limit Theorem 2.cpp

Hackerank/The Central Limit Theorem  3.cpp
=> Create The Central Limit Theorem  3.cpp

Gfg/Anagram_Recursion.java, Gfg/NthNatural.java, Gfg/RearrangingArray.java, Gfg/SaddlePoint.java, Gfg/countEvenDigit_Rec.java
Programs 
Some frequently asked programs and conceptual programs are added like
Anagram using recurrsion
Rearranging Array ( Program in 30 days of Code asked in gfg)
Nth Natural (Program in 30 days of Code asked in gfg)
Find Saddle Point
Count Even Digits using Recursion 
Fixes #Add Programs in Java issue
=> Added few basic conceptual but important programs

Hackerank/Least Square Regression Line.cpp
=> Create Least Square Regression Line.cpp

Hackerank/Multiple Linear Regression.py
=> Create Multiple Linear Regression.py

Hackerank/Arrays: Left Rotation.cpp
=> Create Arrays: Left Rotation.cpp

Hackerank/New Year Chaos.cpp
=> Create New Year Chaos.cpp

Hackerank/Minimum swaps 2.py
=> Create Minimum swaps 2.py

Hackerank/A Very Big Sum.c
=> Create A Very Big Sum.c

Algorithms/Dynamic Problems/Gold Mine Problem.cpp
=> Fixed Create Gold Mine Problem.cpp

Algorithms/Backtracking/print all permutations of a given string.cpp
=> Create print all permutations of a given string.cpp

Algorithms/Divide and Conquer/Closest Pair of Points using Divide and Conquer algorithm.cpp
=> fixed Create Closest Pair of Points using Divide and Conquer algorithm.cpp

Algorithms/Dynamic Problems/Edit Distance.cpp
=> Create Edit Distance.cpp

Algorithms/Coin Change.py
=> fixed Create Coin Change.py

Hackerank/Candies.cpp
Added solution to the problem <a href="https://www.hackerrank.com/challenges/candies/problem">HackerRank Candies.</a>
=> Solution to HackerRank Candies

Algorithms/binary_recursive_search.cpp, Data Structures/Sieve of Eratosthenes.cpp
=> Issue #101(Sieve of Eratosthenes #101) is Solved . Plz merge 

Algorithms/binary_recursive_search.cpp
No need to mention void in int main() funcition.
=> Void commit

Codechef/Charges.cpp, README.md
=> Update ReadMe. Issue #114 . "Few popular coding platform added in Readme section".

Codechef/Charges.cpp, README.md
=>  Update ReadMe. Issue #114 "New line added after Point 8 and 12". Plz merge my update.

Codechef/Charges.cpp, README.md
=> Issue #11  Added question of codechef for interview Qus1 added .

Codechef/Charges.cpp, README.md
Octat image added  to make our readme more attractive.
=> Update README.md Issue #114 . " New Image added to make the README more attractive.

Hackerank/Grading Students.c
=> Create Grading Students.c

Hackerank/Apple and Oranges.py
=> Create Apple and Oranges.py

Hackerank/Number line jumps.py
=> Create Number line jumps.py

Hackerank/Between Two Sets.cpp
=> Create Between Two Sets.cpp

Hackerank/Breaking the records.py
=> Create Breaking the records.py

Hackerank/Subarray Division.c
=> Create Subarray Division.c

Gfg/Detect_Loop_in_linked_list.cpp
Added a new question of detecting loop in a singly linked list using the two pointer algorithm. It is programmed in c++
=> Added Detect_loop_in_linked_list.cpp

Data Structures/Longes_common_sbsequnce.cpp
=> Longest Common Subsequence #Issue 129 resolved.

Hackerank/Staircase.cpp
=> Solution to HackerRank Staircase Problem

Hackerank/Day of the Programmer.c
=> Create Day of the Programmer.c

Hackerank/Migratory Bird.c
=> Create Migratory Bird.c

Hackerank/Drawing Book.cpp
=> Create Drawing Book.cpp

Hackerank/Electronics Shop.cpp
=> Create Electronics Shop.cpp

Hackerank/Bill Division.py
=> Create Bill Division.py

Hackerank/Divisible Sum Pair.c
=> Create Divisible Sum Pair.c

Algorithms/Topological_sort.cpp
Added Code for Topological sort in C++.
Topological sort - It is a sorting algorithm that sorts elements based on how they are arranged. It is Implemented only on Directed Acyclic Graphs.
Fixes #107
=> Sorting Algorithm- Topological Sort

Codeforces/new_password_codeforces.cpp
=> new_password_codeforces #153

Gfg/max_of_size_k_window_using _deque.cpp
Hey @Ayush7614 
This PR fixes issue #161 
Kindly review it .
=> added code for maximum of window size k problem

Algorithms/Backtracking/nQueensPermutationCombination.java
=> Added Solution for NQueens Permutation and Combination Genrator

Algorithms/Backtracking/n-queen.cpp
place n-queens so that no queen hit each other
Fixes #227
=> Create n-queen problem.cpp

Algorithms/Backtracking/Rat in  a Maze.cpp
Rat moves from start to end passing all the hurdles 
here 0 acts as hurdel
1 acts as path to move
Fixes #239 
=> Rat in a Maze

Algorithms/PrimeFactorization.cpp
Explanation:
while( num ! = 1 ):
We keep on dividing it with its smallest prime factor.
The smallest prime factor is pre-calculated using a slightly modified prime sieve.
Since we start from 2 and go on, we mark the first multiple as the spf.
Preprocessing for Sieve: O(n log log n)
Time Complexity for factorization: O(log n)
Space Complexity: O(n)
Fixes #245
=> PrimeFactorization.cpp

Codechef/SpaceArrays.java
Added the java code for the question named space arrays on codechef. 
Question code: SPACEARR
Fixes #244 
- [✅] New feature (non-breaking change which adds functionality)
- [✅] My code follows the style guidelines(Clean Code) of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] My changes generate no new warnings
=> Added solution to Space Arrays #244

Data Structures/Spiral Order Matrix.cpp
The code prints the 2D matrix in spiral order. 
Fixes #220 
=> Create Spiral order Matrix

Data Structures/string_tokenizer.cpp
Issue number : #105, This file contains the string tokenizer program with strtok() and the inner working code of strtok().
=> Issue no : #105, Adding string_tokenizer file 

Codechef/pattern_codechef.py
=> Pattern23(codechef)

Algorithms/Searching and Sorting/Ternary_search.cpp
I have added the Ternary search algorithm in the CPP language
Fixes #221
=> added Ternary search

Gfg/SpiralDisplay.java
This is the code of the Spiral display in Java. With required comment
Fixes #(211)
The java implementation is done by me.
=> Added the code of Spiral Display in Gfg implement in Java

Hackerank/Pairs.java
Added a new file Pairs.java
This problem was not there previously, I have added it.
Fixes:  #305
**Link: https://www.hackerrank.com/challenges/pairs/problem**
**Path: Hackerank/Pairs.java**
This is under **LGM-SOC21**.
=> Added Pairs.java

Algorithms/Searching and Sorting/Shell_sort.py
Created python program too perform shell sort algorithm
Fixes #175 
=> Add Shell_sort.py

Algorithms/Russian_Peasant_Algorith.cpp, Algorithms/Russian_Peasant_Algorithm.cpp
Implemented the Russian Peasant Multiplication algorithm in C++.
The logic behind the algorithm: The value of a*b is the same as (a*2)*(b/2) if b is even, otherwise the value is the same as ((a*2)*(b/2) + a).
Fixes #168
=> Implementation of Russian Peasant Multiplication algorithm in C++

Algorithms/Russian peasant multiplication.py
Created a python program to execute Russian peasant multiplication algorithm
Fixes #168 
=> Add 'Russian peasant multiplication.py'

Data Structures/SeiveOfEratosthenes.java
In this PR, I have added the code for Seive Of Eratosthenes program. I have made it user input & it works fine.
Fixes #309 
Added a program for Seive Of Eratosthenes in Java
=> Add Seive Of Eratosthenes in Java

.vscode/c_cpp_properties.json, Codechef/Covid Analyzer (covin).cpp, Codechef/Pattern7(ITGUY79).cpp, Codechef/pattern23(ITGUY95).cpp
=> Patter 7 added(ITGUY79)

Algorithms/comb_sort.cpp
I have added the code for comb sort in C++
Fixes #352(issue_no)
=> Add Comb Sort

Algorithms/circle_sort.cpp
I have added the code for circle sort in C++
Fixes #350 (issue_no)
=> Add Circle Sort in C++

Data Structures/intersection.java
Input :
firstArray : {1, 1, 1, 2, 4, 5}
secondArray : { 2, 3, 5 }
Output:
outputArray : { 2, 5 }
Fixes #269
Replace `#269` with the issue number which is fixed in this PR
- [ x ] New feature (non-breaking change which adds functionality)
=> Intersection of Sorted Array

Algorithms/Sieve of Eratosthenes.c
Implemented Sieve of Eratosthenes in C programming.
We create an array arr[0..n] and initialize all entries as 1. A value in arr[i] will finally be 0 if i is Not a prime, else 1. We ignore all the non-primes in the range and get the prime numbers.
Fixes #101
=> Implementation of Sieve algorithm in C

Hackerank/Digit Power Sum.py
I am a LGM-SOC participant and contributed the code of Digit Power Sum problem in Hackerank.
Description: Calling a positive integer "interesting" if it contains at least two digits when written in base  and is equal to the sum of its digits raised to some power.
Fixes #307
Replace `307` with the issue number which is fixed in this PR
=> Added Digit Power Sum 

Gfg/Maximise sum in array.cpp
Added the code to maximize the sum of selected numbers from an array to make it empty, in C++ programming language in the GeeksForGeeks folder.
Fixes #257
- Output for given array = {1, 2, 3} ![Output for array = {1,2,3}](https://user-images.githubusercontent.com/68430517/121476203-ffb8ea80-c9e3-11eb-94b2-f9d98e62b23c.PNG)
=> Added code to maximize the sum of selected numbers from an array

Gfg/MaximizeSum.java
=> Maximize the sum (java code)

Data Structures/LinkedList.cpp
This program will take user input for linked list elements and then traverse them.
=> Create Linked List in C++

Codeforces/Balanced_Rating_Changes._codeforces.cpp
=> Balanced Rating Changes question on codeforces #273

Gfg/Allocate_minimum_number_of_pages.cpp
Hey @Ayush7614 @Amit366 
This PR Fixes: #165
kindly review it .
=>  issue-165 resolved

Gfg/Trapping Rain Water.cpp
Fixes #297
Replace `297` with the issue number which is fixed in this PR
Added trapping rain water problem with self explanatory code in cpp
=> Create Trapping Rain Water.cpp

Gfg/Allocate_minimum_number_of_pages.cpp, Gfg/count_occurrences_of_element.cpp
hey @Ayush7614 @Amit366 
This PR fixes issue-162
kindly review it.
=> Issue 162 Resolved 

Gfg/Subset Sum Prob.cpp
Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum.
Fixes [#252](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/252)
=> Added the code for Subset Sum problem

Gfg/Subset Sum Prob.cpp, Leetcode/Target_Sum.cpp
Question:
You are given an integer array nums and an integer target.
You want to build an expression out of nums by adding one of the symbols '+' and '-' before each integer in nums and then concatenate all the integers.
For example, if nums = [2, 1], you can add a '+' before 2 and a '-' before 1 and concatenate them to build the expression "+2-1".
Return the number of different expressions that you can build, which evaluates to target.
Fixes [#250 ](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/250)
=> Added code for Issue250

Minimum_swaps_required.cpp
=> #290 Minimum No of Swaps

Gfg/maximum_sum_circular_array.cpp
Added maximum circular subarray sum
Fixes #326
new file added
- [ 1] My code follows the style guidelines(Clean Code) of this project
- [ 1] I have performed a self-review of my own code
- [1 ] I have commented my code, particularly in hard-to-understand areas
=> Issue #326

Algorithms/Greedy Algorithms/Maximum sum removing k numbers.cpp
Added solution to Maximum  Sum question
Fixes #242
=> Added Maximum Sum Answer

Algorithms/Adjacent Difference Algo
#286 issue Folder changed
Fixes #286
=> Create Adjacent Difference Algo

Gfg/Reversearray.cpp
Reverse array in cpp (easiest form)
Fixes #389
=> Added reverse array in cpp

Codechef/Expedition(Expedi).cpp
Issue Number. #222 
Thanks for letting me work on this project.
=> Added Expedition Problem

Algorithms/Rabin-Karp Algo
Code Written in Java
Fixes #397
=> Create Rabin-Karp Algo

Data Structures/Union of two sorted array.py
=> Union of sorted array in python

Algorithms/Searching and Sorting/DNF.cpp
=> DNF (Dutch National Flag)

Gfg/01 Knapsack.cpp
Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack. In other words, given two integer arrays val[0..n-1] and wt[0..n-1] which represent values and weights associated with n items respectively. Also given an integer W which represents knapsack capacity, find out the maximum value subset of val[] such that sum of the weights of this subset is smaller than or equal to W. You cannot break an item, either pick the complete item or don’t pick it (0-1 property).
=> 0/1 Knapsack Recursive Code

Data Structures/array implementation of stack.c
Includes push and pop function
Fixes #258
=> Array implementaion of stack in DATA STRUCTURES

Gfg/Good_or_Bad_String.cpp
I have added [Good or Bad string](https://practice.geeksforgeeks.org/viewSol.php?subId=eec439a99970aedb0e6b77d14cd83a1e&pid=85&user=ujjwalcomputerpro1) #GFG Problem using c++
Fixes: #323
=> added Good or Bad string.cpp

Algorithms/Wave sort.cpp
Hey @Ayush7614 
Check this PR. This will fix this issue.
=> Added the code for Wave Sort Problem

Algorithms/Bubble Sort.cpp
I have added Bubble Sort algorithm with proper implementation in CPP which wasn't there before.
Fixes #216 
=> Added Bubble sort algo in this folder

Algorithms/Disjoint Set/union_find_algorithm.cpp
Added a c++ file implementing the union find algorithm of disjoint set.
Fixes #395
=> union find algo of disjoint set added

Gfg/Sort 0s 1s 2s.cpp
I have provided the C++ code for the the above program .
Issue #248 
Please review my code.
=> Sort 0s 1s 2s added

Data Structures/nextgreatorelement.cpp
I have made this using array data structure in c++.
#238
=> next greator element

Hackerank/concentric square pattern.c
I added a Program for Concentric square pattern using 2D array In C in Hacker Rank File 
Fixes #194 
=> Concentric square pattern using 2D array In C Fixes #194 please merge this code 

Hollow Butterfly.cpp
=> Hollow Butterfly

Codechef/hollow butterfly pattern.py
=> Hollow butterfly pattern

Algorithms/Dynamic Problems/Largest Sum.cpp
The solution to the largest sum issue added.
Fixes #243 
=> Largest Sum Solution Added

Algorithms/Searching and Sorting/BubbleSort_Comparisons_Count.cpp
Fixes : #367 
I added a file named "BubbleSort_Comparisons_Count.cpp" in Algorithms->Searching and Sorting.
I have added Bubble Sort.
This program will have a menu asking about users choice which are as follows
"1. Automatic input from 1-100"
"2. Custom Input"
"3. Exit"
If user choses option 1 i.e. automatic input then the program will print a table at different intervals of size and prints the number of comparisons done at the best, worst and average cases at this size.
If user choses option 2 i.e. custom input then the program will ask the size of array and the elements inside it and then will print the result and the number of comparisons.
This programs will be helpful to know the working of algorithms as on what type of case(best, worst or average) how comparisons occur in the logic.
=> Counting Number Of Comparisons in Bubble Sort

Algorithms/Dynamic Problems/longest_increasing_subsequence.java
Fixes #231
Replace `#231` with the issue number which is fixed in this PR
=> added Longest_Increasing_Subsequence ( issue #231) in java

Gfg/count-occurence-of-an-element-in-array.c
I have solved this issue in C language for the issue number #251 for finding the occurence of an element in an array.
@Ayush7614  Please review my code and kindly merge my branch temp.
Sample Input :  10
5
1 2 2 3 4
here 10 is the size of array, 5 is the length of array.
Sample output :the number  is repeated 2 times.
=> Solved issue number #251 for finding the occurence of the element in an array

Gfg/Subset Sum Prob.cpp, Leetcode/LongestCommonSubsequence.cpp, Leetcode/Target_Sum.cpp
Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.
A subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.
For example, "ace" is a subsequence of "abcde".
A common subsequence of two strings is a subsequence that is common to both strings.
Fixes #[358](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/358)
=> Added code for Issue358 (Longest Common Subsequence - Leetcode(Medium) )

Algorithms/infixToPostfix
Language Used: JAVA
LGM-SOC'21 Contribuition.
Fixes #171
Added Infix To Postfix conversion algorithm
=> Added Infix to Postfix conversion algorithm.

Algorithms/Searching and Sorting/Radix_Sort.cpp
Added Radix Sort in C++ Language
Add Radix sort #537
- 
- [✔️ ] New feature (non-breaking change which adds functionality)
- [ ✔️] My code follows the style guidelines(Clean Code) of this project
- [✔️ ] I have performed a self-review of my own code
- [ ✔️] I have commented my code, particularly in hard-to-understand areas
- [ ✔️] I have created a helpful and easy to understand `README.md`
- [ ✔️] I have made corresponding changes to the documentation
- [ ✔️] My changes generate no new warnings
- [ ✔️] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
=> Added Radix Sort 

Algorithms/Searching and Sorting/RadixSort.java
Fixes #537 
- ![image](https://user-images.githubusercontent.com/58087950/121777096-f3808900-cbad-11eb-9933-e591ed058af4.png)
=> added code for Radix sort

Codechef/LCS-3.cpp
Issue Number: #584 
Thanks for giving me this opportunity to work on this project.
I have done this code in C++ and given proper explanation.
Fixes #584 
=> LCS for 3 Strings

Data Structures/DoublyLinkedList
LGM-SOC'21 Contribuition
Added JAVA implementation of Doubly LL
Fixes #172
=> Added DoublyLinkedList Implementation.

Algorithms/Searching and Sorting/Jump Search
=> Create Jump Search

Algorithms/Searching and Sorting/Jump_search.cpp
I have added Jump search in CPP language in algorithm/searching_and_sorting folder
Fixes #461
=> added Jump search.cpp

Algorithms/call_by_reference.cpp
=> ADDED CODE FOR call_by_reference (issue-151)

Leetcode/FindMinimunInRotatedSearchArray_Leetcode.cpp
Added solution to the Leetcode Question **Find Minimum in Rotated Sorted Array** in C++.
Fixes #590
=> Find Minimun In Rotated Search Array Leetcode Question

Gfg/Count occurrences of an element in a sorted array.py
Python3 program to Count occurrences of an element in a sorted array. 
Approach : Improved Binary Search 
Time Complexity : O(Logn)
Finding occurrences of an element in a sorted array.
Fixes : https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/162
=> Count occurrences of an element in a sorted array.py 

Gfg/AllocateMinimumNumberOfPages.java
Allocate Minimum Number Of Pages question solved
Fixes #165
=> Allocate Minimum Number Of Pages (java)

Leetcode/Tree/SumOfNodesWithEvenValuedGrandparent.java
Language Used: JAVA
LGM-SOC'21 Contribuition.
Fixes #351
Added LeetCode Solution of Sum of Nodes with Even-Valued Grandparent.
=> Added LeetCode Question Solution.

Miscellaneous problems/ConcatenatedWords/ConcatenatedWords.java, Miscellaneous problems/ConcatenatedWords/Question - Concatenated Words, Miscellaneous problems/ConcatenatedWords/concatenatedWordsTest.java, Miscellaneous problems/Template/template.md
Given an array of strings words (without duplicates), return all the concatenated words in the given list of words.A concatenated word is defined as a string that is composed entirely of at least two shorter words in the given array.
Fixes #404
=> Solution for Concatenated Words #404 under LGM-SOC

Data Structures/Tree/TreeTraversal/InOrderTraversal.java, Data Structures/Tree/TreeTraversal/PostOrderTraversal.java, Data Structures/Tree/TreeTraversal/PreOrderTraversal.java
LGM-SOC'21 Contribuition
Fixes #174 
Added Java code of BT traversal.
- InOrderTraversal
- PostOrderTraversal
- PreOrderTraversal
=> BT traversal added

Gfg/Anagaram.c
Implementation of anagram in C programming.
Fixes #100
=> Anagram in C

Algorithms/Dutch National Flag Algorithm.cpp.cpp
=> ADDED CODE FOR Dutch National Flag Algorithm.cpp (issue-148)

Algorithms/Chinese_Remainder_Theorem.cpp
=> ADDED CODE FOR Chinese_Remainder_Theorem (issue-147)

Codechef/smartphone.py, smartphone.py
=> SmartPhone Codechef 

Codechef/Smart Phone (ZCO14003).cpp
Fixes #532 
Added the code for "Smart Phone" problem in codechef (DSA Learning Series)  in c++
Problem name : Smart Phone
Problem Code : ZCO14003
Problem link : https://www.codechef.com/LRNDSA01/problems/ZCO14003
C++
=> Added Smart phone problem of codechef

Data Structures/Intersection of two sorted array.py
=> Intersection of two sorted array in python

Data Structures/max-absolute-difference.cpp, Data Structures/partition_problem.py
Provided solution for the following:
#209 calculating the maximum absolute difference between the sum of two non-overlapping subarrays
#214 Partition Problem using Dynamic Programming
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X ] My code follows the style guidelines(Clean Code) of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
=> Added solution for #209 and #214

Algorithms/call_by_value.cpp
=> ADDED CODE FOR call_by_value issue-152

Data Structures/Rotation_of_Array_by_Kelements.java
java code for rotation of array by k elements
Fixes #167 
- [ x] New feature (non-breaking change which adds functionality)
-  [x] My code follows the style guidelines(Clean Code) of this project
=> Added the java code for rotation of array by k elements

Data Structures/Sieve_of_Eratosthenes.cpp
=> Sieve_of_Eratosthenes.cpp

Algorithms/Searching and Sorting/Bubble Sort in Python
Bubble Sort in Python
Fixes #427
=> Create Bubble Sort in Python

Codeforces/454_B_Little_Pony_and_Sort_by_Shift.cpp
Simple Code which can be understand by a beginner easily in C++ 
Fixes #414
=> 454_B_Little_Pony_and_Sort_by_Shift.cpp

Algorithms/Graph/BFS.java
Fixes #176 
- ![image](https://user-images.githubusercontent.com/58087950/121770686-5f4ffb00-cb88-11eb-9bd0-9d1d096b0035.png)
=> BFS Graph Traversal

Gfg/Palindrome_number.py
I have added solution to palindrome number problem in python.
Fixes #429
=> Added palindrome number solution in python !

Algorithms/Daimond.java, Algorithms/SandGlass.java
=> Adding Daimond & sand glass pattern in java

Data Structures/ReverseArray.py
=> Reverse the array

Codechef/Destroy the EMP (CHAOSEMP).cpp
Added solution of Destroy the EMP (CHAOSEMP) in codechef Folder.
Fixes #598 
- [✓ ] New feature (non-breaking change which adds functionality)
- [✓] My code follows the style guidelines(Clean Code) of this project
- [✓] I have performed a self-review of my own code
- [✓] My changes generate no new warnings
=> Added Destroy the EMP (CHAOSEMP)

Gfg/Diameter of Binary Tree.cpp
I have provided the correct C++ code for Diameter of a binary tree , now it is working properly and even added comments for better understanding of the program.
Fixes #253
=> Diameter of Binary Tree added

Gfg/FriendsPairingProblem.cpp
Friends Pairing Problem in C++ using Dynamic Programming
Fixes #604 
=> Friends Pairing Problem added

Algorithms/Dynamic Problems/bellmanford.c
Bellman Ford Algorithm Implementation in C
Fixes #522 
=> Bellman Ford Algo in C

Algorithms/Searching and Sorting/InsertionSort_Comparisons_Count.cpp, Algorithms/Searching and Sorting/SelectionSort_Comparisons_Count.cpp
Fixes : #370 
I added a file named "SelectionSort_Comparisons_Count.cpp" in Algorithms->Searching and Sorting.
I have added Selection Sort.
This program will have a menu asking about users choice which are as follows
"1. Automatic input from 1-100"
"2. Custom Input"
"3. Exit"
If user choses option 1 i.e. automatic input then the program will print a table at different intervals of size and prints the number of comparisons done at the best, worst and average cases at this size.
If user choses option 2 i.e. custom input then the program will ask the size of array and the elements inside it and then will print the result and the number of comparisons.
This programs will be helpful to know the working of algorithms as on what type of case(best, worst or average) how comparisons occur in the …
=> Counting Number of Comparisons in Selection Sort

Algorithms/Searching and Sorting/InsertionSort_Comparisons_Count.cpp
Fixes : #368 
I added a file named "InsertionSort_Comparisons_Count.cpp" in Algorithms->Searching and Sorting.
I have added Insertion Sort.
This program will have a menu asking about users choice which are as follows
"1. Automatic input from 1-100"
"2. Custom Input"
"3. Exit"
If user choses option 1 i.e. automatic input then the program will print a table at different intervals of size and prints the number of comparisons done at the best, worst and average cases at this size.
If user choses option 2 i.e. custom input then the program will ask the size of array and the elements inside it and then will print the result and the number of comparisons.
This programs will be helpful to know the working of algorithms as on what type of case(best, worst or average) how comparisons occur in the …
=> Counting number of comparisons in Insertion Sort

Algorithms/Recursive Modular Exponentiation
=> Create Recursive Modular Exponentiation

Data Structures/Longest Substring without repeating characters
Ques: Given a string s, find the length of the longest substring without repeating characters.
Example 1:
Input: s = "abcabcbb"
Output: 3
Fixes #233
In c++
=> Longest Substring without repeating characters

Codeforces/watermelon.cpp
=> water melon problem CF #521

Codeforces/Watermelon.c
C solution for issue 521
Fixes #521 
=> C solution for issue 521

Codeforces/Friends_and_Candies_Codeforces.cpp
Codeforces Question **Friends and Candies's** solution has been added.
Fixes #596 
=> Friends and Candies codeforces solution added

Data Structures/Stack-implementation_using_array.cpp
In stack implementation using an array, the stack is formed by using an array and the operations related to the stack like push and pop are performed using arrays.
Fixes #195 
- [✔] New feature (new code added)
- [✔] My code follows the style guidelines(Clean Code) of this project
- [✔] I have performed a self-review of my own code
- [✔] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
=> Stack Implementation using array

Algorithms/Bead_Sort.cpp
I have added the code for Bead Sort in C++
Fixes #550 (issue_no)
=> Add Bead Sort 

Leetcode/Number of Islands.cpp
Greetings sir/ma'am,
I am LGMSOC participant I have added the code for LeetCode problem Number of Islands
Fixes #585
**[Link For the problem]** https://leetcode.com/problems/number-of-islands/
=> Adding  in cpp Number of Islands.cpp

Leetcode/NumberOfIslands.java
Fixes #585 
- ![image](https://user-images.githubusercontent.com/58087950/121776857-bb2c7b00-cbac-11eb-96dc-7a7ed2a9cf2b.png)
=> java solution for number of islands

Codechef/Coin Flip (CONFLIP).cpp
Fixes #517 
Added Coin Flip Problem of Codechef
Problem name : Coin Flip
Problem Code : CONFLIP
Problem link : https://www.codechef.com/LRNDSA01/problems/CONFLIP
C++
=> Added "Coin Flip" problem of codechef

Algorithms/Dynamic Problems/flodyWarshall.c
Add a Floyd Warshell Algorithm in C
Fixes #431
@Ayush7614 @Amit366 please review it
=> Add a Floyd Warshell Algorithm in C

Gfg/TrappingWater.java
Added Rain water trapping  problem in Java in gfg folder.
Fixes #297
=> Add Rain Water Trapping problem in Java

Leetcode/Maximum_Subarray.cpp
Implemented the Maximum Subarray Leetcode problem in c++
Fixes #962
=> Added Maximum Subarray in c++

Algorithms/Brian_Kernighan's_Algorithm.cpp
=> ADDED CODE FOR Brian_Kernighan's_Algorithm (issue-847)

Algorithms/Graph/DijsktraAlgo.java
Fixes #559 
- ![image](https://user-images.githubusercontent.com/58087950/121775162-8d8f0400-cba3-11eb-9fd9-246ecbb6813c.png)
=> added code for  Dijsktra algorithm in java

Hackerank/Encryption.java
Added solution of Encryption in Java under LGMSOC'21.
Fixes #314
=> Added  solution of Encryption in Java.

Gfg/reverse_array.c
=> Added reverse array.c file

Gfg/Get_Maxinmum_Maze_Paths.java
=> ADDED CODE FOR ADDED CODE FOR Get_Maxinmum_Maze_Paths (issue-150)

Codechef/Birthday_gift.c++
Fixes #182
Replace `182` with the issue number which is fixed in this PR
- [
=> Birthday Gift question of Codechef under issue #182 for LGM-SOC

Data Structures/Morris.c
=> Morris Order Traversal

Codeforces/570_B_Simple_Game.cpp
So I Divided that question into different Cases and then wrote a beginner friendly solution : )
Fixes #411 
=> 570_B_Simple_Game (Codeforces)

Leetcode/Next_permutation_of_a_number.py
Added python code to find the nearest permutation of a number 
Fixes #249
=> Added Next_permutation_of_a_number.py

Gfg/Sort012.py
I have added a problem which sorts array containing 0s ,1s and 2s
Fixes #248
=> Added sort array containing 0,1 and 2

Gfg/Disjoint_set.cpp
Added disjoint set application problem in c++.
Fixes #548
=> Added disjoint set application problem in c++

Gfg/find_largest_sum_contiguous_subarray.cpp
An efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers that has the largest sum. 
Fixes #783
=> Largest sum contiguous Subarray problem's code added

Gfg/Generate_balanced_parenthesis.cpp
Hey @Ayush7614  @Amit366 
This PR fixes issue - #198.
kindly review it.
=> iadded code for issue-198

Gfg/reverseLinkedList.java
Reverse Link List solved in Java
Fixes #432
=> Reverse Link List (java)

Gfg/Armstrong.java
Armstrong number in java
Fixes #430
=> Armstrong number (java)

Codechef/CARVANS.cpp
Fixes #795 
Added the code for "Carvans" problem in codechef (DSA Learning Series) in c++
Problem name : Carvans
Problem Code : CARVANS
Problem link : https://www.codechef.com/LRNDSA01/problems/CARVANS
C++
=> Added "Carvans" problem of codechef

Codeforces/1367B_Even_Array.cpp
Added Solution to Even Array Problem of Codeforces.
LGM-SOC'21
Fixes #738 
=> Added Solution of Even Array problem

Algorithms/Searching and Sorting/Interpolation.cpp
=> Interpolation_Search.cpp

Algorithms/InterpolationSearch.c
Added Interpolation search algo in C.
Fixes #659
=> Added Interpolation search algo in C

Algorithms/Greedy Algorithms/dijsktra_algo.c
Dijkstra's Algorithm in C
Fixes #559
=> Dijsktra Algo in C

Gfg/RotateArray.py
=> Added rotate array in python !

Gfg/LeftRotationOfArray.java
Java solution for issue 688
Fixes #688 
=> Java solution for issue 688

Hackerank/Left Rotation array.c
Fixes #688 
I have added solution of Left Rotation Array Problem from Hackerrank.  The solution is in the C language.
Please review my solution and merge pull request.
=> Added HackerRank problem Left Rotation

Codeforces/twins.cpp
I have added the twins program from code forces in c++ language.
Fixes #747 
=> Twins program from code forces

Algorithms/Searching and Sorting/Shell Sort.cpp
=> Create Shell Sort.cpp

Algorithms/Krushal's Algo.cpp
=> Create Krushal's Algo.cpp

Algorithms/Searching and Sorting/interpolationSearch.cpp
Added a interpolation search in C++
Fixes #422
@Ayush7614 @Amit366 please review it
=> Added a interpolation search in C++

Algorithms/Searching and Sorting/Ubiquittous_Binary_Search.cpp
=>  Ubiquittous_Binary_Search.cpp

Algorithms/BellmanFord.cpp
This PR is in accordance with issue #652
=> Added BellmanFord algorithm

Codeforces/Rank_List.cpp
This Rank_List.cpp is solution of the ques Rank List of codeforces.
Ques tag - 166 A in codeforces
Fixes #623
- Following is the screenshot of output for 1st testcase,
=> Added Rank List ques of Codeforces

Codechef/Coins And Triangle (TRICOIN).py
Fixes #792 
Added the code for "Coins and Triangles" problem in codechef in Python
Problem name : Coins And Triangle
Problem Code : TRICOIN
Problem link : https://www.codechef.com/problems/TRICOIN
Python
=> Added "Coins and Triangles" problem of codechef in python

Leetcode/KthMissingPositiveNumber.py
Added leetcode question of kth missing positive number in python
Fixes #383 
=> Added LeetCode Kth missing positive number in python

Leetcode/KthMissingPositiveNumber.cpp
Added Kth missing positive number in C++
Fixes #383 
=> Added LeetCode Kth missing positive number question in C++

Algorithms/Backtracking/ratInMaze.py
Added Rat In Maze Algorithms Solutions in Python Language
Fixes #423
@Amit366 please review it
=> Added Rat in Maze solution In python

Gfg/Chocolate Distribution Problem.cpp
This contains the C++ solution of the Chocolate Distribution Problem.
Fixes #300
=> #300 Chocolate Distribution Problem

leetcode/Hamming.java
- I have written the code for hamming distance in java.
- All the test cases are passed successfully.
Fixes #581
=> Added hamming distance in java

AtCoder DP /A-Frog1.cpp
Added c++ solution of problem A of AtCoder DP Contest
Fixes #189
=> Added solution of problem A of AtCoder DP Contest

Algorithms/longest increasing subsequence.cpp
=> longest increasing subsequence

Gfg/move_negative_element_to_one_side.c
I want to provide the solution for issue no #254 moving all negative elements to one side. in C language
Sample Input: 10
6
-1 1 -2 3 4 -5
Sample Output: 
-1 1 -2 3 4 -5(Before operation)
-1 -2 -5 1 3 4(After operation)
=> addig solution for  issue no. #254 moving negative elements to one side in C language

Algorithms/dfs_entry_exit_time.cpp
Added dfs_entry_exit time c++ file, which calculates the entry and exit time of each vertex in dfs traversal.
Fixes #673
- Following is the screenshot of output,
=> Added dfs entry exit time in algorithm section

Codechef/LKDNGOLF.cpp
I have added the code in c++ language for it.
Question: https://www.codechef.com/MAY21C/problems/LKDNGOLF/
Fixes #769 
Replace issue_no with the issue number which is fixed in this PR
=> LKDNGOLF from CodeChef

Codechef/Bitwise tuples(BITTUP).cpp
This is the solution of Bitwise Tuples from CodeChef in C++.
Question: https://www.codechef.com/JUNE21C/problems/BITTUP
Fixes #768 
=> Bitwise Tuples from CodeChef

Codechef/Lapindromes.py
=> Lapindromes codechef in Python

Algorithms/Dynamic Problems/Product_of_Self_Array.java
=>  Product_of_Self_Array.java

Codeforces/Way Too Long Words.c
C solution to issue 653
Fixes #653 
=> C solution to issue 653

Data Structures/PairwiseSwap.c
Pairwise swapping in a linked list ( swapping of adjacent nodes pairwise by changing links instead of swapping data )
Fixes #680 
=> Pairwise Swap using Linked List added

Leetcode/peakIndexinAMountainArray.cpp
* Added [Peak Index in a Mountain Array](https://leetcode.com/problems/peak-index-in-a-mountain-array/) Question of Leetcode
Fixes #626
=> Added peakIndexOfMountainArray

Leetcode/LargestNumber_Leetcode.cpp
Solution of Leetcode question Largest Number (Medium) has been added in C++ language.
Fixes #679
=> Largest Number Leetcode question added

Codechef/Summerheat.c
I have added a Summer heat Code chef  June long challenge solution under Code chef  folder in C. @Amit-45 Please review this PR. This will Fix issue #734 .
Please delete options that are not relevant.
=> Added code for Summer heat Code chef June long challenge-Div3

Codechef/coin_triangle_problem.cpp
Describe the solution you'd like
Problem Code: TRICOIN
Problem Link: https://www.codechef.com/problems/TRICOIN
Fixes #792 
- [✔] New feature (new code added)
- [✔] My code follows the style guidelines(Clean Code) of this project
- [✔] I have performed a self-review of my own code
- [✔] I have commented on my code, particularly in hard-to-understand areas
=> Coin_triangle_problem.cpp

Data Structures/diameter_of_binary_tree.cpp
=> ADDED CODE FOR diameter_of_binary_tree (issue-866)

Hackerank/Flatland Space stations.java
Added solution of Flatland space stations in Java under LGMSOC'21
Fixes #312
=> Added solution of Flatland space stations in Java under LGMSOC'21

Algorithms/Graph/Top_View_in_Binary_Tree.cpp
=> Top_View_in_Binary_Tree.cpp

Data Structures/reverse_LL.cpp
=> added code for linked list in  c++

Codeforces/Way_too_long_words.py
Python3 solution to issue 653
Fixes #653
=> python3 solution for issue #653

Hackerank/Fibonacci Modified.py
Added Solution of Fibonacci Modified in Python under LGMSOC'21
Fixes #316
=> Added Solution of Fibonacci Modified in Python under LGMSOC'21

Hackerank/Recursive digit sum.py
Added solution of Recursive digit sum in Python under LGMSOC'21.
Fixes #319
=> Added solution of Recursive digit sum in Python under LGMSOC'21

Gfg/minimumjumptoreachend.cpp
Signed-off-by: Harsh kumar <68609382+harsh6768-svg@users.noreply.github.com>
This code uses the concept of dynamic programming and is used to find the minimum no of jumps needed to reach end of array
Fixes #924
Replace #924 with the issue number which is fixed in this PR
No changes just updated the code
=> Code for Minimum no of jumps to reach end of array in c++

Data Structures/Setbitposition.py
@Amit-45 Please review this PR. This will fix this issue #742  
=> Added code for finding position of Set bit in python

Hackerank/The time in words.java
Added Solution of The time in words in Java under LGMSOC'21
Fixes #716
=> Added Solution of The time in words in Java under LGMSOC'21

Algorithms/Graph/Kahn's Algo.cpp
=> Kahn's Algo.cpp

Codechef/Lapindromes (LAPIN).cpp
Fixes #707 
Added the code for "Lapindromes" problem in codechef (DSA Learning Series) in c++
Problem name : Lapindromes
Problem Code : LAPIN
Problem link : https://www.codechef.com/LRNDSA01/problems/LAPIN
C++
=> Added "Lapindromes" Problem of Codechef in C++

Codechef/Bella_ciao.py
Added Bella ciao in python !
Fixes #753
=> Added bela ciao in python

Codechef/Bella_ciao.java
Fixes #753 
I have added the code in java language in the codechef folder.
=> Bella Ciao from codechef

Gfg/CircularTour.java
Language: JAVA
Added GFG Solution.
- Circular Tour
Fixes #736 
=> Added GFG Solution.

Gfg/pascal.py
Pascal's Triangle
Fixes #508 
Language: Python
=> Pascal's Triangle (python)

Codechef/Tsort.py
=> TSORT Codechef Problem

Gfg/kth_maximum_term_in_an_array.cpp
Code added for finding the Kth maximum/ minimum element in array in a menu driven format. 
Fixes #765
=> GFG-Find the Kth maximum and minimum element of an array

Data Structures/Zig-Zag_Binary_Tree_Traversal.cpp
I have added the C++ code for Zig-Zag Traversal of a Binary Tree.
Fixes #709
=> Zig-Zag Traversal added

Leetcode/binary_tree_from_inorder_and_preorder.py
This pull request contains the solution to a Leetcode problem that is to construct a binary tree from a given preorder and inorder traversals. This includes the addition of a file named "**binary_tree_from_inorder_and_preorder.py**".
Link of the problem: [**Construct Binary Tree from Preorder and Inorder Traversal**](https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/)
Fixes #186 
=> Adding solution to Create Binary Tree from Inorder and Preorder Traversal under LMGSOC-21

Gfg/spiral_print.cpp
Spiral print a 2D array in c++
Fixes #676
=> Added spiral print 2D array in c++

Algorithms/Dynamic Problems/Equal_sum_Partition.cpp
I have added code for Equal Sum partition problem in which we have been given a set of positive numbers, and we have to find if we can equally divide the set into two subsets such that the sum of elements in both the subsets is equal.
Fixes #782
Replace #782  with the issue number which is fixed in this PR
=> Added code for Equal Sum Partition Problem using Dynamic Programming (C++).

Algorithms/Dynamic Problems/RegularExpressionMatchingAlgorithm.py
Regular Expression Matching Algorithm Added in DP
Fixes #484 
=> ReMatching Algorithm with "*" & "."

Data Structures/Prefixtoinfix.py
@Amit-45 Please review this PR. This will solve issue #758 .
=> "Added code for prefix to infix expression in python"

Gfg/RemoveDuplicatesFromSortedArray.cpp
Added : Remove Duplicates from sorted array in c++ using an auxillary array.
Fixes #923 
=> Remove Duplicates from Sorted Array added

Codeforces/Pythagorean_Triples(Problem_1487D).cpp, Codeforces/Pythagorean_Triples(Problem_1487D).java
Added Problem Pythagorean Triples (1487D) of Codeforces in C++ and JAVA
Fixes #1132 
- New feature (non-breaking change which adds functionality)
=> Adding Codeforces Problem 1487D in C++ and JAVA

Algorithms/Dynamic Problems/LexicographicallySmallestPermutation.py
Lexicographically Smallest Permutation code added in DP
Fixes #483
=> Lexicographically Smallest Permutation

Leetcode/First_Bad_Version.cpp
Implemented the Leetcode problem no. 278- First Bad Version in c++ with time complexity O(logn)
Fixes #965
=> Added First Bad version - Leetcode

Hackerank/LuckyNumber.py
Implementation of program to find lucky numbers using python.
A number is called lucky if the sum of its digits, as well as the sum of the squares of its digits is a prime number. How many numbers between a and b inclusive, are lucky?
For ex. a=20, b=25
Lucky numbers are : 21,23 and 25
Fixes #771
=> Lucky Number

Gfg/DetectCycleInLinkedlist.java
I implemented this task using java. this is Gfg problem where this solution passed all testcase.
Fixes #934
=> Add Detect cycle in linkedlist

Algorithms/pascaltriangle.c
fixes issue #508 
please review my PR @Amit-45 
thanks :)
=> Issue 508 in c

Hackerank/Balanced_brackets.py
Added solution to problem balanced brackets in hackerrank .
Fixes #665
=> Balanced brackets

Leetcode/Minimum_window.cpp
Added solution to Minimum window question. Language used - CPP.
Fixes #669 
=> Minimum window substring in CPP solution added

Gfg/Maxsubarray.py
Added maximum sum of subarray in python.
Fixes #783 
=> Added maximum sum of subarray in python

Gfg/Staircase_search.cpp
I have added staircase search in 2D array in cpp.
Fixes #895
=> Added staircase search in 2D array

Data Structures/prefix_infix.cpp
Conversion of Prefix expression to Infix expression using C++ 
Fixes #758 
=> Prefix to Infix code added

Codechef/gold_coin.py
Added bytelandian gold coin problem from codechef 
Fixes #1249
=> Added gold coin problem codechef

Codechef/Bytelandian gold coins.cpp
This is a solution to : https://www.codechef.com/problems/COINS
Fixes #1249 
=> Create Bytelandian gold coins.cpp

Algorithms/Backtracking/NQueens.java
Fixes #672 
- ![image](https://user-images.githubusercontent.com/58087950/122111122-fb099180-ce3c-11eb-969c-01dbd5c799f1.png)
=> solution for n queens in java

Hackerank/Balanced Brackets.cpp
=> Solution of Balanced Brackets

Algorithms/Searching and Sorting/Bucket_Sort.py
Bucket sort, or bin sort, is a sorting algorithm that works by distributing the elements of an array into a number of buckets.
Fixes #991 
=> Bucket Sort Added in Python

Gfg/Generate_Balanced_parenthesis.py
Added a beginner Friendly Code .
-Easy to understand 
-Comments and approach added
Fixes #198 
=> Generate_Balanced_parenthesis.py

Codechef/Shortest_Route.cpp
Hello @prudhvirajstark @cmulay @VinayakMohite4040 @shantamsultania @Sumanth2905  sir, I have added the code for issue #1023 Shortest Route Problem from CodeChef, sir can you please review my code,
Fixes #1023
=> Added the code for Shortest_Route.cpp

Gfg/SinglyLinkedListInsertionSort.cpp
Added : Sorting Singly Linked List using Insertion Sort in C++
Fixes #928 
=> Sorting Singly Linked List using Insertion Sort added

Algorithms/Longest Consecutive Sequence.cpp
Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.
Fixes #(1222)
=> Longest-Consecutive-Sequence

Algorithms/Dynamic Problems/BooleanParenthesization.py
Boolean Parenthesization Problem in DP
Fixes #917
=> Boolean Parenthesization Problem in DP

Algorithms/WarnsdorffAlgorithm.java
WarnsdorffAlgorithm code added in Algorithm
Fixes #922
=> WarnsdorffAlgorithm code added in Algo

Gfg/Union_of_2_sorted_arrays.py
I have added union of 2 sorted arrays in python.
Fixes #1163
=> Added union of 2 sorted arrays

Gfg/max_subtree_sum.py
Added maximum subtree sum in python.
Fixes #1231
=> Maximum subtree sum in python

Algorithms/sorting.cpp
bubble sort
insertion sort
merge sort has been used and user can do whichever he want by removing the comments from the calling function.
here all the different types of sorting has been unified .
=> three types of soring has been added .

Data Structures/RemoveDuplicatesFromSortedArray.java
Added program in java to remove duplicates from a sorted array.
Fixes #923
=> Added program in java to remove duplicates from a sorted array

Kahn’s Algorithm for Topological Sort.cpp
I have solved issue no.225 in c++.
=> Kahn’s Algorithm for Topological Sort.cpp

Data Structures/Stack_operation.cpp
Added code which consist all stack operations using array and linked list Implementation.
LGM-SOC'21
Fixes #1000 
=> Add Solution to all Stack Operations

Leetcode/Longest_valid_parenthesis.java
This pull request contains the solution to Leetcode problem that is to find longest valid parenthesis using dp in Java. This includes the addition of file named "Longest_valid_parenthesis.java" in Leetcode folder.
Link of the problem: https://leetcode.com/problems/longest-valid-parentheses/
Fixes #756
[✔] My code follows the style guidelines(Clean Code) of this project
[✔] I have performed a self-review of my own code
[✔] I have commented my code, particularly in hard-to-understand areas
=> Added solution of Leetcode problem: Longest valid parenthesis in java

Leetcode/Min_No_Of_Refueling_Stops.java
This pull request contains the solution to Leetcode problem that is to find minimum number of refueling stops using dp in Java. This includes the addition of file named "Min_No_Of_Refueling_Stops.java" in Leetcode folder.
Link of the problem: https://leetcode.com/problems/minimum-number-of-refueling-stops/
Fixes #757 
[✔] My code follows the style guidelines(Clean Code) of this project
[✔] I have performed a self-review of my own code
[✔] I have commented my code, particularly in hard-to-understand areas
=> Added Solution of Leetcode problem: Minimum No. of Refueling Stops in java

Codeforces/taxi.java
I have added taxi question solution in java language
Fixes #1119 
=> Taxi program from code forces in java

Algorithms/LinkedList/Reverse_a_sublist_of_a_list.cpp
Added the reverse a sublist of a LinkedList Program in Algorithms/LinkedList
Fixes #872
=> Added Reverse a sublist of a LinkedList

Codechef/Hail_XOR.cpp
Hello @prudhvirajstark @cmulay @VinayakMohite4040 @shantamsultania @se-prashant @  sir, I have added the code for the  "Hail XOR" Problem of CodeChef #1237, sir, can you please review my code,
Fixes #1237
=> Added the code for Hail_XOR.cpp

Gfg/binaryInsertionSort.java
Added solution of Binary Insertion Sort in gfg folder.
Fixes #551
=> Binary Insertion Sort (java)

Leetcode/maximum rectangular area in histogram.cpp
Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.
Input: heights = [2,1,5,6,2,3]
Output: 10
Fixes #(237)
=> maximum rectangular area in histogram.cpp  

Leetcode/ValidMountainArray.cpp
Added the solution to the leetcode problem valid mountain array.
Fixes #1011
=> Added valid mountain array

Gfg/palindrome.cpp
I've added palindrome program in c++
Fixes #429
=> added palindrome.cpp

Gfg/Add two numbers represented by linked lists.cpp
This contains the solution of  the problem Add two numbers represented by linked lists mentioned  in issue no. (#306) in C++.
Fixes #(306 )
=> Add two numbers represented by linked lists solution

Data Structures/Detect Cycle In Undirected Graph.cpp
Given an undirected graph with V vertices and E edges, check whether it contains any cycle or not.
Fixes #(issue_no 1016)
=> Create Detect Cycle In Undirected Graph.cpp

Gfg/TripletswithZeroSum.cpp
Added : Finding triplets with zero sum in an array in C++
Fixes #1372 
=> Finding triplets with zero sum in an array added

Gfg/Total_Set_Bits.java
Added Count Total Set Bits Problem in GFG folder.
Fixes #1368
=> Count Total Set Bits

Gfg/rangeQuery.cpp
added range Query code in C++ in the GFG section
Fixes #741
=> added rangeQuery code in GFG

Leetcode/minimumWindow.java
Minimum Window code added in LeetCode 
Fixes #669
=> Minimum Window in Java

Algorithms/Searching and Sorting/KMP_Algorithm.py
Added KMP_Algorithm in python 
Fixes #740 
=> KMP_Algorithm.py

FenwickTree.c
Fenwick Tree Implementation in C
Fixes #610 
=> Fenwick Tree Implementation

Leetcode/String into Integer.cpp
=> Create String into Integer.cpp

Data Structures/Min_Element_In_Stack.java
Addition of Reversing Circular LinkedList
**Name of the File** - Min_Element_In_Stack.java
**Destination Folder** - Daily-Coding-DS-ALGO-Practice/Data Structures/
Fixes #1097
=> Added Min_Element_In_Stack.java

Codeforces/Twins.java
@Amit-45 Please review this PR. This will fix the issue #747 .
=> Added code for twins question from code forces in java

Gfg/CHOCOLA–Chocolate.cpp
We are given a bar of chocolate composed of m*n square pieces. One should break the chocolate into single squares. Parts of the chocolate may be broken along the vertical and horizontal lines as indicated by the broken lines in the picture.
A single break of a part of the chocolate along a chosen vertical or horizontal line divides that part into two smaller ones. Each break of a part of the chocolate is charged a cost expressed by a positive integer. This cost does not depend on the size of the part that is being broken but only depends on the line the break goes along. Let us denote the costs of breaking along consecutive vertical lines with x1, x2, ..., xm-1 and along horizontal lines with y1, y2, ..., yn-1.
The cost of breaking the whole bar into single squares is the sum of the …
=> CHOCOLA CHOCLATE code added

Gfg/Largest subarray with 0 sum .cpp
Aim:
Given an array having both positive and negative integers. The task is to compute the length of the largest subarray with sum 0.
Fixes #(1312)
This problem is solved in language C++.
=> Create Largest subarray with 0 sum .cpp

Algorithms/power_of_2_(Bit_Manipulation).py
=> power_of_2_(Bit_Manipulation).py

Codechef/Strong_Language SSCRIPT.c
Added solution(well commented with explanation) to the Codechef problem 'Strong Language' in C language
Problem Code: SSCRIPT
Link to the problem:https://www.codechef.com/APRIL21C/problems/SSCRIPT
Fixes #1387
=> Added solution to codechef problem Strong Language

Data Structures/Minimum and maximum value in a Binary Tree.cpp
This contains the solution of the problem to find the Minimum and Maximum value in a Binary Tree in C++.
Fixes #(190)
=> Minimum and Maximum value in a Binary Tree

Algorithms/Dynamic Problems/Equal_sum_Partition.java
Fixes #782 
- ![image](https://user-images.githubusercontent.com/58087950/122889835-c62b9c00-d360-11eb-879f-4018780b3f6f.png)
=> Equal sum partition problem in java

Data Structures/TowerOfHanoi.py
Added Tower Of Hanoi in python.
Fixes #206
=> Added Tower Of Hanoi in python

Data Structures/BFSGraph.c
Added BFS Graph traversal in C.
Fixes #176
=> Added BFS Graph traversal in C

Gfg/Shortest Path From 1 to n .cpp
Consider a directed graph whose vertices are numbered from 1 to n. There is an edge from a vertex i to a vertex j if either j = i + 1 or j = 3 * i. The task is to find the minimum number of edges in a path in G from vertex 1 to vertex n.
Fixes #(issue_no :1366)
=> Create Shortest Path From 1 to n .cpp

Data Structures/Postfix_Evaluation.cpp
Added Postfix Evaluation Solution using Stack Data Structure in Data Structure Folder.
Fixes #937 
=> Added Postfix Evaluation Solution using Stack

Leetcode/kids-with-the-greatest-number-of-candies.cpp
Added Solution of Kids with Greatest Number of Candies Problem of Leetcode
Fixes #1241 
=> Added Solution of Kids with Greatest Number of Candies Problem

Codechef/ICPC_BALLOON.py
added ICPC BALLOON problem in CODECHEF
Fixes #1334
=> added ICPC BALLOON problem in CODECHEF

Codeforces/Deleting_divisors.py
Added Deleting divisors problem of codeforces in python.
Fixes #1376
=> Added deleting divisors

Codeforces/Kuriyama_Mirai's_Stones.pp.cpp
Added the solution of codeforces question Kuriyama Mirai's Stones in c++.
In this the algorithm  used is segment tree.
The question code for this problem is 433 - B
Fixes #1149
Below is the screenshot of output for particular input,
=> Added solution of Kuriyama Mirai's Stones ques in codeforces

Data Structures/histogram.c
Implemented Problem to find maximum rectangular area in histogram using C
Fixes #237 
=> Maximum rectangular area in histogram code added

Algorithms/Graph/DFSGraphValidation.cpp
added DFS Graph code in Graph 
Fixes #739
=> added DFS Graph code in Graph

Leetcode/online_stock_span.cpp
I have added solution of "Online Stock Span" ( in cpp ) under Leetcode folder.
Fixes #1210 
=> added online_stack_span.cpp Problem in Leetcode

Algorithms/LinkedList/Sorted_LinkedList_to_BST.cpp
added LinkedList to BST program in c++ (Algorithms/LinkedList)
Fixes #1003
=> Add LinkedList to BST program

Codechef/Total Expenses.java
Added solution of Total Expenses in Java under LGMSOC'21
Fixes #1203
=> Added Total Expenses of Codechef in Java under LGMSOC'21

Hackerank/Athelete-Sort-Python.py
Added Athelete sort solution in Python along with the problem in HackerRank Folder.
Fixes #458
=> Add Athelete sort in Python in HackerRank

Data Structures/Reverse_Circular_Linkedlist.cpp
I have added a C++ code for reversing a circular linked list in the Data Structure folder
Fixes #990
=> Reverse Circular Linked List added

Leetcode/String_to_atoi_(Leetcode-Medium).py
Added my code for String to Int (atoi) in python
Fixes #798 
=> String_to_Int-(atoi)_(Leetcode-Medium).py

Hackerank/lucky_number.cpp
Finding lucky number between two numbers using C++
Fixes #771 
=> lucky number code

Gfg/Lucky_Person_Alive.java
- Added Lucky Alive person problem in java.
Fixes #1208
=> Added Lucky Alive Person in GFG folder

Gfg/range_of_array.py
I have added a Program to find range of Array in python !
Fixes #1329
=> Added range of array in python !

Gfg/union_arrays.py
Added union of 2 sorted arrays in python 
Fixes #1147
=> Added union of 2 sorted arrays in python

Leetcode/Add Two Numbers In Linklist.cpp
You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.
You may assume the two numbers do not contain any leading zero, except the number 0 itself.
Fixes #(issue_no 1449)
=> Create Add Two Numbers In Linklist.

Codeforces/Indian Coin Change.cpp
Hey @Ayush7614 @Amit366 
Added the Indian Coin Change Problem in C++
Please check and update.
Thanks
Fixes #730 
=> Indian Coin Change Problem in C++

Data Structures/remove_dup.c
Remove duplicates from unsorted list code in C
Fixes #892
=> Remove duplicates from unsorted linked list code 

Codechef/BitwiseTuples.cpp
=> Added Bitwise Tuples

Codeforces/Marvolo_Gaunt's_Ring.cpp
Marvolo Gaunt's Ring Problem solved in c++ using dynamic programming.
Fixes #204
=> Marvolo Gaunt's Ring  in cpp

Algorithms/Graph/graph_col.c
Fixes #(https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/932#issuecomment-861866457)
Graph coloring in c in 0(v *m time)
=> Graphcol_in_c

Gfg/Multiply two linked lists.cpp
This contains the solution of Multiply two linked lists problem present in GFG in C++.
Fixes #304
=> Multiply Two Linked Lists

Algorithms/Searching and Sorting/Sparse_search.cpp
Hey @Ayush7614 @Amit366 @Saurabh4626 @ravikr126 
This PR fixes issue #1039
Kindly review it .
=> Sparse Search Algorithm

Codechef/Chefland Visa (VISA).py
Fixes #1289 
Added the code for "Chefland Visa" problem in codechef (June Cook-Off 2021) in python
Problem name : Chefland Visa
Problem Code : VISA
Problem link : https://www.codechef.com/problems/VISA
Python
=> Added "Chefland Visa" Problem of Codechef in Python

Codechef/cheflandvisa.c
I have added the code of chef land visa problem in c language.
Fixes #1289 
=> Chefland Visa from code chef

Codechef/cheflandvisa.java
Added the code for chefland visa in java language
Fixes #1289 
=> Chefland visa from code chef in java 

Codechef/Total_Expenses.cpp
I have Added Solution of Total Expenses Problem of Codechef.
LGM-SOC'21
Fixes #1203 
=> Added Solution of Total Expenses Problem of Codechef

Data Structures/Merge Point of Two Linked List.cpp
=> solution of Merge Point of Two Linked List

Codeforces/DeletingDivisors.cpp
Fixes #1376 
- ![image](https://user-images.githubusercontent.com/58087950/123504018-4c532580-d674-11eb-85cc-6bc008ef54c9.png)
=> Deleting Divisors code in c++

Codeforces/dice_tower.cpp
=> Dice tower codeforces #1213

Codechef/XOR Folding (XOREQUAL).cpp
Fixes #1439 
Problem name : XOR Folding
Problem Code : XORFOLD
Problem link : https://www.codechef.com/COOK130C/problems/XORFOLD
C++
=> Added "XOR Folding" Problem of Codechef in c++

Codechef/xor_folding.java
I have added the program for xor folding problem in Java language.
Fixes #1439 
=> Xor folding problem from code chef

Codeforces/False Numbers.java
Added code for False Numbers (June LunchTime)
Fixes  #1491
=> False Numbers (June LunchTime)

Codechef/HTML_Tags.java
Add Html tags code added.
Fixes #1490 
=> Html Tags (June Lunchtime)

Data Structures/merge_ll.cpp
Implemetation of code for merging two sorted linked list using C++
Fixes #1333
=> Merge two sorted linked list

Codechef/Small Factorials.py
Added Solution of Small Factorials in Python under LGMSOC'21
Fixes #1201 
=> Added Solution of Small Factorials in Python under LGMSOC'21

Data Structures/Stack/largest_rectangle.cpp
to find the largest rectangle with the height using  the stack.
Fixes #1436 
=> largest rectangle

Gfg/Bellman_Ford.java
Bellman Ford Algorithm in Java solved
Fixes #652
=> Bellman Ford (java)

Codechef/Turbo Sort.java
=> Added Turbo Sort.java files in Codechef folder

Leetcode/Smallest_positive_missingno.py
Added first missing positive element in an array in python.
Fixes #1230
=> Added smallest positive missingno

Palindrome Linked List.cpp
AIM 
Given the head of a singly linked list, return true if it is a palindrome.
Fixes #(issue_no 1547)
=> Create Palindrome Linked List.

Codeforces/Unlucky_Ticket.cpp
In this added the solution to the codeforces problem Unlucky Ticket.
The problem Code is 160 B.
Fixes #1250
Below is the screenshot of the output for a given input,
=> Added Unlucky Ticket Problem in Codeforces

Codechef/CyclicQuad.py
Cyclic Quad CodeChef added in Codechef
Fixes #1569
=> Cyclic Quad CodeChef

Delete a given Node when a node is given.cpp
Write a function to delete a node in a singly-linked list. You will not be given access to the head of the list, instead you will be given access to the node to be deleted directly.
It is guaranteed that the node to be deleted is not a tail node in the list.
Fixes #(issue_no 1450)
=> Create Delete a given Node when a node is given

Codechef/false_number.cpp
Added code for False Numbers (June LunchTime)
Fixes #1491
=> Added False number code (June Lunchtime)

Leetcode/Power-Of-Four.cpp
Added Solution to the problem: Power of Four
I have added 3 different approaches.
Fixes #1408
=> Added Problem- Power of Four

Leetcode/Group_Anagrams.cpp
Added code for Group Anagrams in C++.
Fixes #1508
=> Added code for group anagrams (Leetcode) under LGMSOC'21

Leetcode/Combination_Sum.cpp
I  am LGM-SOC participant and added the C++ code for Combination Sum Problem on Leetcode.
Description: Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may return the combinations in any order.
Fixes #746
Replace `746` with the issue number which is fixed in this PR
=> C++ code for Combination_Sum

Algorithms/Dynamic Problems/Buy and Sell stock atmost k transactions.cpp
I am a LGM-SOC participant and I want to contribute the code of Buy and sell stock problem in C++.
Description: You are given an integer array prices where prices[i] is the price of a given stock on the ith day, and an integer k.
Find the maximum profit you can achieve. You may complete at most k transactions
Fixes #318
Replace `318` with the issue number which is fixed in this PR
=> C++ code for Buy and Sell stocks  (atmost k transactions)

Codechef/Minimum Dual Area.cpp
=> Create Minimum Dual Area.cpp

Leetcode/pascal_triangle.cpp
Resolved issue #1244 
I have added this question in the C++ language. 
The Brute force and Optimized approach are there with some examples.
=> Pascal Triangle added 

Gfg/PairsWithGivenSum.cpp
Signed-off-by: Harsh kumar <68609382+harsh6768-svg@users.noreply.github.com>
Just We will Find the Pair with the given sum in doubly linked list 
For eg:
Input : head : 1 <-> 2 <-> 4 <-> 5 <-> 6 <-> 8 <-> 9
x = 7
Output: (6, 1), (5,2)
Fixes #1232
Replace #1232 with the issue number which is fixed in this PR
=> Pair with Given Sum In Doubly Linked List

Codeforces/DiceTower.java
This pull request contains the solution to Codeforces **round#139** **problem A Dice Tower** in java. This includes the addition of file named "DiceTower.java" in Codeforces folder.
Link of the problem: https://codeforces.com/contest/225/problem/A
Fixes #1213 
- [✔ ] My code follows the style guidelines(Clean Code) of this project
- [ ✔] I have performed a self-review of my own code
- [✔ ] My changes generate no new warnings
=> Added Solution of Dice Tower in Java

Codechef/Factorial.py
Finding the factorial of a number 
Fixes #1454
=> Finding Factorial

Hackerank/bigdecimal.java
Added the solution of JAVA BigDecimal program from hacker rank.
Fixes #1487 
=> BigDecimal from hacker rank

Codechef/From Rational to Binary.java
Added code for CodeChef problem From Rational to Binary.
Fixes #1495
=> From Rational to Binary(Codechef LunchTime)

Algorithms/LinkedList/Reverse_LinkedList_in_a_group_of_given_size.cpp
Added Problem in algorithm Linked List folder with proper comments
Fixes #1375
=> Add Reverse a LinkedList in a group of given size

Codechef/Chess_Match.java
Code for chess match  (Codechef Starters) added.
Fixes #1512 
=> Chess Match (Codechef Starters)

Codechef/Total Correct Submissions.java
Code for Total Correct Submissions(Codechef Starters).
Fixes #1510
=> Total Correct Submissions(Codechef Starters)

Codeforces/I_Hate_1111(Problem1526B).cpp
Adding Problem "I Hate 1111" (1526B) of Codeforces in C++
Fixes #1129 
- New feature (non-breaking change which adds functionality)
=> Adding Problem 1526B of codeforces in C++

Codechef/queries.cpp
I have added the code in c++ language.
Fixes #1515 
=> Chef and Queries from code chef

Codechef/chefqueries.java
Added the code in JAVA language.
Fixes #1515 
=> Chef and Queries from codechef in java

Leetcode/josephus_problem_recursion.cpp
This a Josephus Problem.
The problem is named after Flavius Josephus, a Jewish historian living in the 1st century. According to Josephus' account of the siege of Yodfat, he and his 40 soldiers were trapped in a cave by Roman soldiers. They chose suicide over capture and settled on a serial method of committing suicide by drawing lots.
Fixes #674 
=> Josephus problem added using C++

Codeforces/Sleep_Cycle.java
Sleep cycle code added in java
Fixes #1511
=> Sleep Cycle (Codechef Starters)

Codechef/Discrepancies_in_the_Voters_List  VOTERS.c
Added the example test cases.
Fixes #1415
=> Sakinanomi patch 1

Data Structures/Priority_Queue.cpp
- I have Added All Priority Queue Operations like Enqueue, Dequeue, Display using Array and Linked List Implementation in a single Code.
- LGM-SOC'21
Fixes #1286 
=> Added All Priority Queue Operations using Array and Linked List 

Data Structures/odd_even_seggregate.c
Implementation of code Segregate even and odd nodes in a Linked List using C
Fixes #1513
=> Added odd even segregate code

Data Structures/Reverse_ll_using_Stack.cpp
- Added Solution of Reverse Linked List Using Stack Data Structure
- LGM-SOC'21
Fixes #1287 
=> Added Code for Reverse Linked List Using Stack

Data Structures/Binary_Search_Tree.cpp
- Added All Operations of Binary Search Tree
- LGM-SOC'21
Fixes #1442 
=> Added all operation of Binary Search Tree

Codeforces/Unlucky_ticket.py
Added unlucky Ticket from codeforces 
Fixes #1250
=> Added unlucky ticket in python.

Data Structures/Klee's Algorithm.cpp
I have added the C++ code for Klee's Algorithm
Fixes #1505 
Please review my code
=> Klee Algorithm added

Algorithms/Dynamic Problems/FloydWarshall.cpp
Added the code of FloydWarshall algortihms using Cpp
Fixes #1123
=> FloydWarshall in C++

Algorithms/Dynamic Problems/FloydWarshall.java
Adding the code of FloydWarshall in Java
Fixes #1123
=> FloydWarshall in Java

Algorithms/Dynamic Problems/FloydWarshall.py
Added FloydWarshall code in Python
Fixes #1123 
=> FloydWarshall in python 3

Codeforces/Indian Coin Change.py
Added the code for Indian Coin Change Problem in Python.
Fixes #730 
=> Added solution for Indian Coin Change Problem in Python

Gfg/uglynum.cpp
=> Ugly Number

Gfg/celebrity_problem.cpp
Added code for Celebrity Problem in C++ language under LGMSOC'21.
Fixes #1546
=> Added code for Celebrity problem (GFG)

Gfg/Palindromic partitioning.cpp
Added Palindromic partitioning problem in gfg folder;
Fixes #1635
=> Create Palindromic partitioning.cpp

Leetcode/shortest_supersequence.py
Added shortest supersequence in python.
Fixes #1274
=> Added shortest supersequence 

Data Structures/rangeminmax.c
Range means the difference between the maximum and minimum element in the array.
Sample Input: 6
-1 -2 -3 4 5 6
Sample Output: 7
@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 i have provided the solution In C language for issue no. #1329.
Kindly merge it after analyzing.
=> added the solution for finding the range of array in C language for issue no. #1329

Gfg/Find_n_in_array.py
Added check if n is present in array of size m in python.
Fixes #1331
=> Find n in array of size m

Leetcode/trappingRainWater.cpp
Added the Problem from Leetcode: Trapping Rain Water
Fixes #1550
=> Added New Problem - Trapping Rain Water

Codechef/Relativity.java
Added code for problem termed as relativity in (July Long Challenge) 
Fixes #1686
=> Relativity (July Long Challenge)

Gfg/peak_element.cpp
Peak element code implementation using C++
Fixes #1640 
=> Peak element code added

Leetcode/permutations.cpp
Added the Problem from Leetcode: Permutations
Fixes #1623
=> Added Problem Permutations

Algorithms/perfect_no.cpp
Implementation of code to find maximum number of Perfect Numbers present in a subarray of size K using C++
Fixes #1641
=> Maximum perfect number code added

Data Structures/connected_components.c
Implementation of program to count number of connected components in an undirected graph
Fixes #1599
=> Connected components code added

Leetcode/product_array_except_self.cpp
Added a program to get the product of the array except self
Fixes #1624
=> Added a program to see a product of a array except self

Leetcode/Majority Element.cpp
Added a function to solve the majority element problem where the array is sorted first and then the index at n/2 is returned.
Fixes #1618  
=> Added Cpp Solution to Majority Element

Leetcode/AddBinary.cpp
C++Solution for "Add Binary" on LeetCode
Fixes #1725 
=> Solution for "Add Binary" on LeetCode for Issue #1725

Codeforces/I_Hate_1111(Problem1526B).java
Adding Problem "I Hate 1111" (1526B) of Codeforces in C++
Fixes #1129 
-  New feature (non-breaking change which adds functionality)
=> Adding Problem 1526B of codeforces in JAVA

Codeforces/Mountain_Scenery.cpp, Codeforces/dice_tower.cpp
=> Chetas shree mountain #1295

Data Structures/Tree/postorder_traversal.py
Added postorder traversal of a Binary Tree in python
Fixes #1005
=> Added postorder traversal in python

Algorithms/Dynamic Problems/B Frog2.cpp
Added problem B of AtCode Dp in Algorithm/DynamicProblem.
Fixes #1118
=> Added problem B of AtCoder DP

Leetcode/First_missing_positive_num.java
Fixed #1230
The following code finds the positive number missing in the unsorted array. Its s a leetcode hard problem 
Time complexity: O(N)
Link to the problem : https://leetcode.com/problems/first-missing-positive/
Fixes #1230
A sample test case has been attached below:
=>  First missing positive number in unsorted array. (in java)

Data Structures/npresentornot.c
added solution for issue number #1331 in C language
n is the number u want to check which would given by the user.
Sample Input:
5
2
1 2 3 4 5
Output : present/not present
Check	whether	n	is	present	in	an	array	of	size	m	or	not.
@Ayush7614 @Amit366 @ravikr126 @Saurabh4626 i have provided the solution In C language for issue no. #1331.
Kindly merge it after analyzing.
=>  added solution for issue number #1331 in C language

Leetcode/RomanToInt.cpp
C++ Solution for "Roman to Integer" on LeetCode under LGMSOC21
Fixes #1741 
@Amit366 @ravikr126 @Ayush7614
=> C++ Solution for "Roman to Integer" on LeetCode under LGMSOC21

Data Structures/fixed_parities.cpp
I have added the solution of the problem named "Fixed Parities".
Fixes #1669
=> Solution for Fixed Parities

Algorithms/Greedy Algorithms/Police and Thieve.cpp, Leetcode/maximum rectangular area in histogram.cpp
Add Police and Thieve problem in c++/greedy folder
Fixes #1463
=> add Police and Thieve.cpp

Gfg/Sieve of Eratosthenes.cpp
Fixes #1560 
I have added solution of problem using Sieve of Eratosthenes method. Kindly review it.
- [✔] My code follows the style guidelines(Clean Code) of this project
- [✔] I have performed a self-review of my own code
- [✔] I have commented my code, particularly in hard-to-understand areas
- [✔] My changes generate no new warnings
=> Added Sieve of Eratosthenes method solution

Data Structures/Year_to_min_sec_hour_day.cpp
Added Code for Year to Month,Day,Hours,Minutes,Seconds.
Fixes #1760 
=> Added year Conversion Solution

Hackerank/Magic Square.cpp
Added solution for hackerank forming a magic square problem in C++.
Fixes #1485 
=> Magic Square

Algorithms/Greedy Algorithms/Job Sequencing Problem.py, Hackerank/Magic Square.cpp
Solved the job sequencing problem using greedy method in python.
Fixes #1656
=> Job Sequencing Problem

Algorithms/Longest_Consecutive_Sequence.py
Fixes #1222
I have written the code in python.
=> Longest Consecutive Sequence using Python

Codechef/Chess Match (BLITZ3_2).cpp
Fixes #1512 
Problem name : Chess Match
Problem Code : BLITZ3_2
Problem link : https://www.codechef.com/START5C/problems/BLITZ3_2
C++
=> Added "Chess Match" Problem of June CodeChef Starters in c++

Codechef/Total Correct Submissions (TOTCRT).cpp
Fixes #1510 
Problem name : Total Correct Submissions
Problem Code : TOTCRT
Problem link : https://www.codechef.com/START5C/problems/TOTCRT
C++
=> Added "Total Correct Submissions" Problem of June CodeChef Starters in c++

Gfg/Remove_Duplicate_Elements_from_Unsorted_LL.java
> provided solution for Remove Duplicate element from unsorted linked list.
Fixes #1603
=> Added Solution for Remove Duplicate Element from Unsorted Linked List

Codechef/Sleep Cycle (SLPCYCLE).cpp
Fixes #1511 
Problem name : Sleep Cycle
Problem Code : SLPCYCLE
Problem link : https://www.codechef.com/START5C/problems/SLPCYCLE
C++
=> Added "Sleep Cycle" Problem of June CodeChef Starters in C++

README.md
=> Spell error under LGM SOC 2021

Codeforces/Shower_Line.cpp
Added solution to codeforces question Shower Line
Problem Code : 431 - B
Fixes #1522
Below are screenshot of output :
=> Added Shower Line solution in Codeforces

Detect Cycle in Linklist.cpp
AIM 
Given a linked list of N nodes. The task is to check if the linked list has a loop. Linked list can contain self loop.
Fixes #1581
=> Create Detect Cycle in Linklist.cpp

Leetcode/IntToRoman.cpp
C++ Solution for "Integer to Roman" on LeetCode under LGMSOC21
Fixes #1745 
@Amit366 @ravikr126 @Ayush7614
=> C++ Solution for "Integer to Roman" on LeetCode under LGMSOC21

Gfg/sieve_of_eratosthenes.py
Added sieve of eratosthenes in python
Fixes #1560 
=> Added sieve of eratosthenes in python

Data Structures/Center_Of_Star_Graph.cpp
I have added the C++ code for Center of a Star Graph
Please review my code 
fixes #1507
=> Center of Star Graph Added

Data Structures/Reverse a link list using stack.cpp
Reverse Linked List Using Stack Data Structure using C++.
Fixes #1287 
=> Reverse Linked List Using Stack.cpp

Hackerank/Day-of-the-programmer.java
Added solution of Day-of-the-programmer in Java with some example test cases under LGMSOC'21
Fixes #1445 
=> Added Solution of Day-of-the-programmer in java under LGMSOC'21

Codeforces/1-based index of lucky number.cpp
Added solution for Codeforces problem (1-based index of lucky number) in C++.
Fixes #1461 
=> Added 1-based index of lucky number.cpp file

Leetcode/Regular_Expression_Matching(hard).cpp
Added solution to leet code problem Regular Expression Matching
Fixes #1643
Below are the screenshot of output :
=> Added Regular_Expression_Matching(hard) solution in LeetCode

Codechef/unpleasant_ones.cpp
Implementation of unpleasant ones code using C++
Fixes #1494
=> unpleasant ones code added

Leetcode/Max_Consecutive_Ones_III.cpp
=> Added the Max Consecutiev Ones III.cpp

Leetcode/Pascal's_Triangle_II.cpp
C++ Solution for Pascal's Triangle II on LeetCode under LGMSOC21
Fixes #1827 
=> C++ Solution for Pascal's Triangle II on LeetCode under LGMSOC21

Leetcode/SkyLine.cpp
Added the code in c++ language
Fixes #1613 
=> The Skyline problem from leetcode

Codechef/Dense Graph (DENSEGRP).cpp
Added Dense Graph(DENSEGRP) solution of Codechef.
Fixes #1590
=> added Dense Graph (DENSEGRP) of Codechef in C++ under LGMSOC'21 

Algorithms/rabin_karp_algorithm.py
Adden Rabin Karp Algorithm in Python language
Fixes #1631
=> Added Rabin Karp Algorithm in Algorithm

Algorithms/MCM_Memoisation.cpp
Given a sequence of matrices, find the minimum number of multiplications to multiply these matrices efficietly.
Fixes [#1573 )](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/1573)
=> Issue 1573-Matrix Chain Multiplication - DP Algorithm

Leetcode/palindromic_substrings.cpp
Code added for Palindromic Substrings in C++ under LGMSOC'21
Fixes #1777
=> Code added for Palindromic Substrings

Leetcode/Reorganize Strings.cpp
=> Added code for Reorganize Strings of leetcode # fixes 1770

Gfg/last_index_of_array.py
Added last index of an array in python.
Fixes #1690
=> Added last index of an array in python.

Gfg/Lastindex.cpp
Added last index of an array in c++
Fixes #1690 
=> Added last index of an array

Miscellaneous problems/Number's_last_index_in_array/REC_ARR.c
…Miscellenous problems folder
I have added the file for the code of issue #1690 in Miscellenous problems folder\Number's_last_index_in_Array\.
=> File for code for getting last index of element in array is added in 

Gfg/Geek_onacci.cpp
Geek created a random series and given a name geek-onacci series.
our aim is to find the Nth number of the series.
Fixes #1747 
=>  Geek_onacci.cpp

Codechef/Total_Correct_Submissions.cpp
Added C++ Implementation for problem Total Correct Submissions (Codechef TOTCRT).
Fixes #1545  
=> added total_correct_submissions

Leetcode/count_and_say.cpp
Code Added for count and say in C++ language under LGMSOC'21
Fixes #1835
=> Code Added for count and say

Leetcode/Deepest Leaves Sum.cpp, Leetcode/remove nth node from end of list.cpp
=> Fixes #1806 and #1839

Leetcode/Combination Sum.cpp
Solution for Combination Sum of LeetCode
Fixes [#1562](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/1562)
=> Created Combination Sum.cpp

Gfg/Bitonic_Point.cpp
Fixes #1578 
Problem name : Bitonic point
Problem link : https://practice.geeksforgeeks.org/problems/maximum-value-in-a-bitonic-array3001/1#
C++
=> Added Bitonic point

Gfg/Find_n_in_array.cpp
Cpp solution to issue 1331
Fixes #1331 
=> Cpp solution to issue 1331

Codeforces/ChatRoom.java
Java solution to issue 1377
Fixes #1377 
=> Java solution to issue 1377

Algorithms/Bucket_Sort_JAVA.java
Added Bucket Sort in JAVA 
Fixes #991 
- New feature (non-breaking change which adds functionality)
=> Added Bucket Sort in JAVA

Gfg/Next Greater Element.cpp
It contains solution of Next greater element using stack in C++.
Fixes #1318
=> Solution of Next greater element using stack 

Gfg/Job Sequencing Problem.cpp
Aim 
Given a set of N jobs where each job i has a deadline and profit associated to it. Each job takes 1 unit of time to complete and only one job can be scheduled at a time. We earn the profit if and only if the job is completed by its deadline. The task is to find the maximum profit and the number of jobs done.
Note: Jobs will be given in the form (Job id, Deadline, Profit) associated to that Job.
Fixes #1222
=> Create Job Sequencing Problem.cpp

Hackerank/Day_Of_a_Programmer.cpp
C++ solution to issue 1445
Fixes #1445 
=> C++ solution to issue 1445

Gfg/first_index_of_array.cpp
Added  first index of array in cpp
Fixes #1689
=> Added  first index of array in cpp

Gfg/merge_two_sorted_linkedlists.py
Added merge 2 sorted linked list in python .
Fixes #1333 
=> Added merge 2 sorted linked list 

Data Structures/move_all_negative.cpp
I have written solution of  problem "Move all negative numbers at beginning"
Fixes #1766 
=> Solution for move all negative numbers at beginning

Gfg/word_wrap.cpp
Code added for Word Wrap in C++ under LGMSOC'21.
Fixes #1870
=> Code added for Word Wrap

Leetcode/Fruits into Baskets.cpp, Leetcode/Permutation in string.cpp
=>  Fixes #1858 and #1859

Data Structures/Tree/sum_replacement.cpp
Implementation of sum replacement of binary tree using c++
Fixes #1481
=> added sum replacement

Leetcode/Max Length of Subarray.py
Provided the python code for Maximum Length of Repeated Subarray-Python
Fixes #(1899)
issue #1899 
- [.] New feature (non-breaking change which adds functionality)
- [. ] My code follows the style guidelines(Clean Code) of this project
- [.] I have performed a self-review of my own code
- [. ] I have commented my code, particularly in hard-to-understand areas
- [. ] My changes generate no new warnings
- [.] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
=> Added solution for repeated subarray issue #1899

Gfg/clone_linked_list_with_next_and_random_pointer.cpp
Code added for Clone linked list with next and random pointer in C++.
Fixes #1893
=> Code added for clone_linked_list_with_next_and_random_pointer

Leetcode/StringtoInteger.py
@Amit366 Please review this PR. This will fix the issue #798
=> "Added code for StringtoInteger(atoi) in python"

Data Structures/kthmaxmin.java
@Amit366 Please review this PR. This will fix the issue #765
=> Added code for kth max min in java

Gfg/wave_array.java
Added Solution for Wave array in Gfg folder.
Fixes #1577
=> Added Wave Array

Gfg/Sum_of_nodes_on_the_longest_path_from_root_to_leaf.cpp
Code added for Sum of nodes on the longest path from root to leaf node in C++
Fixes #1913
=> Sum of nodes on the longest path from root to leaf node

Codeforces/1547_B_Alphabetical_String.cpp
- Added Solution of Problem B Alphabetical String of Codeforces Round 731
- LGM-SOC'21
Fixes #1920 
=> Added Solution of Alphabetical String Problem of Codeforces

Gfg/largest_BST.cpp
Code added for largest BST in C++ .
Fixes #1914
=> largest BST

Data Structures/xor_challenge.cpp
I have written solution of problem "Move all negative numbers at beginning"
Fixes #1824 
=> Solution for A XOR Challenge

Leetcode/contains-duplicate.java
Added solution of contains-duplicate(Leetcode) in java along with some example test cases.
Fixes #1400 
=> Added solution of contains-duplicate (Leetcode) in Java.

Leetcode/C++/ClimbStairs.cpp
C++ Solution for "Climbing Stairs" on LeetCode under LGMSOC21
Includes both iterative and recursive-memoisation methods.
Fixes #1952 
@Amit366 @ravikr126 @Ayush7614 
=> C++ Solution for "Climbing Stairs" on LeetCode under LGMSOC21

Leetcode/ShortestCommonSupersequence.cpp
Given two strings s1 and s2 and we have to find the length of shortest supersequence consisting of both s1 and and s2.
Shortest Common Supersequence finds the shortest supersequence which consist of all the characters of both the string in the order specified. Supersequence have the same relative order but may or may not be continuous.
Fixes [#1025](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/1025) 
=> Issue 1025 - Shortest Common Supersequence

Data Structures/Max_XOR_of_Two_Array.cpp
I have added the C++ code for Maximum XOR of Two Array
Please review my code 
fixes #1474
=> Maximum XOR of Two Array added

Hackerank/MagicSquare.java
Added Forming a Magic Square problem code to Hackerrank folder.
Link to the problem: https://www.hackerrank.com/challenges/magic-square-forming/problem
Fixes #1485
=> Added Forming a Magic Square problem code to Hackerranck folder

Codechef/dividingStamps.c
Solution to the codechef problem dividing stamps
Fixes #1727
=> Solution to Dividing Stamps question

Data Structures/BinarySearch.java
=> I have solve BinarySearch using JAVA.

Gfg/Main.java
[cryptography]Hill Cipher  done in JAVA
Fixes #1359
_
=> [cryptography]Hill Cipher

Leetcode/Sudoku_Solver.cpp
Added solution to the leetcode problem "Sudoku Solver".
Langusge : C++
Fixes #1684
=> Added Sudoku Solver in LeetCode

Gfg/All_indices.py
Added all indices of a number in array.
Fixes #1691
=> Added all indices of a number in array.

Gfg/gold_mine.py
Gold Mine problem implemented using python.
Fixes #611
=> Gold mine 

Leetcode/C++/First unique character in a string.cpp, Leetcode/C++/Number of 1 bits.cpp
=> added code for count number of 1 bits

Leetcode/Java/Number of 1 Bits.java
Java-Solution Number Of 1 Bits
Easy 3 Line Java solution for "Number Of 1 Bits" using bit manipulation. 
Fixes #1945 
Replace #1945 with the issue number which is fixed in this PR
=> Java-Solution Number Of 1 Bits

Leetcode/firstunquiecharacter.java
First Unique Character in a String under LGMSOC'21 
done this problem in java for issue number #1921 
Fixes #1921 
Replace#1921 with the issue number which is fixed in this PR
code change
=> First Unique Character in a String under LGMSOC'21 for issue #1921

Gfg/Java/Parenthesis_Checker.java
Added solution for [Parenthesis Checker](https://practice.geeksforgeeks.org/problems/parenthesis-checker2744/1) in GFG/java folder.
Fixes #1931
=> Added solution for Parenthesis Checker in GFG folder

Gfg/C++/normal_BST_to_Balanced_BST.cpp
Code added for  Normal BST to Balanced BST in C++
Fixes #1971
=>  Normal BST to Balanced BST

Gfg/Java/All indices of number in an array.java
Added java-solution for  "All indices of number in an array" using simple recursion method.
Fixes #1691 
Replace #1691  with the issue number which is fixed in this PR
=> Java-Solution All indices of number in an array

Data Structures/Indiancoinchange.c
@Amit366 @Ayush7614 Please review this PR. This will fix issue #730
=> Added code for Indian coin change problem

Leetcode/Pow(x,n).py
Added Solution of Pow(x,n) (LeetCode) in Python under LGMSOC'21
Fixes #1538 
=> Added Solution of  Pow(x,n) (Leetcode) in Python

Leetcode/Median of Two Sorted Arrays.java
Code added for Median of Two Sorted Arrays along with test case and main function.
Fixes #1422
=> Code added for Median of Two Sorted Arrays

Gfg/thirdlargestElement.cpp
I added code to find the third largest element in the given array in C++ under the GFG folder.
Fixes #779
=> added file for finding third largest element in array

Leetcode/Python/median_of_2_sorted_arrays.py
Added median of 2 sorted arrays in python
Fixes #1422
=> Added median of 2 sorted arrays in python

Leetcode/C++/Binary tree level order traversal.cpp
=> Added code for binary tree level order traversal

Leetcode/C++/Binary Tree Maximum Path Sum.cpp, Leetcode/C++/Binary tree level order traversal.cpp
=> Added code for binary tree maximum path sum

Gfg/Java/Rotate Matrix 90 degree.java
Easy Java Solution for Rotate Matrix 90 degree
Fixes #1874 
Replace #1874 with the issue number which is fixed in this PR
=> Java-Solution Rotate Matrix 90 degree

Gfg/C++/Detect cycle in an undirected graph.cpp
Code added for Detect cycle in an undirected graph in C++
Fixes #1990
=> Detect cycle in an undirected graph

Gfg/C++/Rotten Oranges.cpp
Code added for Rotten Oranges in C++.
Fixes #1991
=> Rotten Oranges

Gfg/C++/Add two fractions.cpp
Add two fractions in C++ 
Fixes #2030
=> Add two fractions 

Leetcode/C++/Serialize and Deserialize Binary tree.cpp
=> Added code for serialize and deserialize bt

Hackerank/C++/Birthday Cake Candles.cpp
Code added for Birthday-Cake-Candles in C++
Fixes #2003
=> Birthday Cake Candles HackerRank

Leetcode/C++/Subtree of another tree.cpp
=> added code for subtree of another tree

Hackerank/C++/Vector-Sort.cpp
Code added for Vector-Sort in C++
Fixes #2012
=> Vector-Sort HackerRank

Hackerank/C++/Vector-Erase.cpp
Code added for Vector-Sort in C++
Fixes #2014
=> Vector-Erase HackerRank

Hackerank/C++/Sets-STL.cpp
Code added for Sets-STL in C++
Fixes #2015
=> Sets-STL HackerRank

Hackerank/C++/Maps-STL.cpp
Code added for Maps-STL in C++
Fixes #2016
=> Maps-STL HackerRank

Leetcode/C++/Path Sum III.cpp
Code added for Path Sum III in C++
Fixes #2023
=> Path Sum III

Algorithms/Searching and Sorting/sort012.java
sort012 in java
Fixes #1768 
Replace 
#1768  with the issue number which is fixed in this PR
=> sort012 in java issue 1768

Gfg/RotateALinkedList.cpp
Given a singly linked list of size N. The task is to rotate the linked list counter-clockwise by k nodes, where k is a given positive integer smaller than or equal to length of the linked list.
Accuracy: 33.33% (Medium)
Fixes [#1647 ](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/1647) 
=> Added code for issue 1647

Leetcode/Combination Sum2.cpp
- Solution for Combination Sum2 of LeetCode
Fixes #1811
=> Create Combination Sum2.cpp

Gfg/Firstindex.py
First index of an array
Fixes #1689
=> First index of an array

Gfg/searchingarray.cpp
searching largest and smallest element in an array
.
Fixes #453 
=> searching largest and smallest element in an array

Leetcode/Check if Sentence is Pangram.cpp
Solve Check if Sentence is Pangram in C++.
Fixes #1744 
=> Check if Sentence is Pangram.cpp

Leetcode/check-if-the-sentence-is-pangram.java
Added solution of check-if-the-sentence-is-pangram (Leetcode) in java with some example test case under LGMSOC'21
Fixes #1537 
=> Added Solution of check-if-the-sentence-is-pangram in java under LGMSOC'21

codejam/Java/ReverSort.java
Added RevertSort 
Fixes #1622 
=> issue #1622 : added ReverSort.java

Gfg/C++/Diagonal Traversal of Binary Tree.cpp
Code added of Diagonal Traversal of Binary Tree in C++.
Fixes #2022
=> Diagonal Traversal of Binary Tree

Hackerank/C++/Plus-Minus.cpp
Code added for Plus-Minus problem in C++
Fixes #2043
=> Plus-Minus HackerRank

Leetcode/C++/SwapNodesInPairs.cpp
C++ Recursive Solution to "Swap Nodes in Pairs" on LeetCode under LGMSOC21.
Fixes #1951 
@Amit366 @ravikr126 @Ayush7614 
=> C++ Recursive Solution to "Swap Nodes in Pairs" on LeetCode under LGMSOC21

Atcoder dp/N - Slimes.cpp
This is a C++ solution of the problem N-Slimes from  very famous Atcoder Dp Series
Fixes #2077
=> Adding the N_Slimes solution in the Atcoder folder

Gfg/C++/Find the number of islands.cpp
Code added for  Find the number of islands in C++.
Fixes #2057
=> Find the number of islands

Gfg/C++/Strongly Connected Components.cpp
Code added for Strongly Connected Components in C++.
Fixes #2056
=> Strongly Connected Components

Codeforces/C++/Fair Playoff.cpp
Added solution to Codeforces question 'Fair Playoff'.
Fixes #2072 (
Added solution to problem "Fair Playoff" in Codeforces Folder in C++ language.
=> Fair Playoff Codeforces Solution

Gfg/C++/search_sorted_matrix.cpp, Gfg/C++/spiral_matrix_gfg.cpp
Description
In this program I have solved a question to display a matrix in it's spiral form.
link: https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix-1587115621/1#
This PR address issue: #1830
[x] New feature (non-breaking change which adds functionality)
=> Display Spiral Form of a Matrix

Gfg/C++/search_sorted_matrix.cpp
Description
In this PR I have solved question to search if a number is present in a sorted array or not using C++.
link:- https://practice.geeksforgeeks.org/problems/search-in-a-matrix-1587115621/1/?category[]=Matrix&category[]=Matrix&page=1&query=category[]Matrixpage1category[]Matrix
Fixes #1831
=>  Searching In row-column sorted Matrix

Gfg/C++/Calculate_nCr.cpp, Gfg/C++/calculate_nPr.cpp
Calculate nCr in C++
Fixes #2095
=> Calculate nCr 

Hackerank/C++/Grading Students.cpp
Code added for Grading Students problem in C++
Fixes #2099
=> Grading Students HackerRank

Gfg/C++/merge_k_sorted_linked_lists.cpp
Code added for Merge K sorted linked lists in C++.
Fixes #2079
=> Merge K sorted linked lists

Leetcode/C++/flood_Fill.cpp
Code added for Flood Fill in C++.
Fixes #2080
=> Flood Fill

Gfg/C++/majority_elements.cpp, Gfg/C++/triplet_less_than_x.cpp
1. Count triplets with sum smaller than X2
2. majority elements
Fixes #2092 #2071
=> triplet_less_than_x.cpp

Leetcode/C++/Validate bst.cpp
=> Added code for valid bst

Leetcode/C++/Open the door.cpp
=> added code for open the door

Miscellaneous problems/Java/numbers.java
this code will help to find two missing number in between the array.
Fixes #2064 
=> missing two numbers.java

Hackerank/C++/Divisible Sum Pairs.cpp
Code added for Divisible Sum pairs problem in C++
Fixes #2108
=> Divisible Sum Pairs- HackerRank

Gfg/C++/steps_by_knight.cpp
Code added for Steps by Knight in C++.
Fixes #2093
=> Steps by Knight

Data Structures/Collinearity_of_three_points.cpp
I have added the C++ code for Collinearity of three points
Please review my code 
fixes #1616
=> Collinearity of three points added

Leetcode/C++/cheapest_flight_with_k_stops.cpp
Code added for  Cheapest Flights Within K Stops in C++ under LGMSOC'21
Fixes #2094
=> Cheapest Flights Within K Stops in C++

Hackerank/C++/Mini-max Sum.cpp
Code added for Mini-Max Sum in C++
Fixes #2044
=> Mini-Max Sum HackerRank

Hackerank/C++/A Very Big Sum.cpp
Code added for A Very Big Sum in C++
Fixes #2042
=> A Very Big Sum- HackerRank

Leetcode/C++/Perfect squares.cpp
=> added code for perfect squares

Hackerank/C++/Bill Division.cpp
Code added for Bill Division problem in C++
Fixes #2107
=> Bill Division- HackerRank

Data Structures/LinkedList/C/dequeue.c
DEQUEUE IMPLEMENTATION IN C
Fixes #1699
=> DEQUEUE IMPLEMENTATION IN C

Gfg/C++/topological_sort.cpp
Code added for  Topological sort in C++ under LGMSOC'21.
Fixes #2124
=> Topological sort

Leetcode/C++/.vscode/c_cpp_properties.json, Leetcode/C++/.vscode/launch.json, Leetcode/C++/.vscode/settings.json, Leetcode/C++/Combination Sum IV Solution.cpp
Added solution of Combination Sum IV . It is a famous leetcode Dp problem mostly asked in interviews.
Fixes #2103 
Replace #2103  with the issue number which is fixed in this PR
=>  Solution of Combination Sum IV

Leetcode/Check If Two String Arrays are Equivalent.java
Fixes #1548 
Replace `#1548` with the issue number which is fixed in this PR
=> merge request for issue 1548

Gfg/maximum xor.java
MAXIMUM XOR IN JAVA
Fixes #1474 
Replace `#1474` with the issue number which is fixed in this PR
code change in java
=> merge request for issue #1474

Leetcode/Java/Delete Node in a Linked List.java
Updated Java-Solution for "Delete Node in Linked list" with main function and examples/test cases.
Fixes #1872 
Replace #1872 with the issue number which is fixed in this PR
=> Updated Java-Solution Delete Node in Linked list

Gfg/Java/Middle of three using minimum comparison.java
Better approach for "Middle Of Three In Minimum Comparison" in java language.
Please merge this PR.
@Amit366 @ravikr126 @Ayush7614 
Fixes #2034 
Replace #2034  with the issue number which is fixed in this PR
=> Java-Solution Middle Of Three

Codeforces/1547_C_Pair_Programming.cpp
- Added Solution of Problem C Pair Programming of Codeforces Round 731.
- LGM-SOC'21
Fixes #1924 
=> Added Solution of Pair Programming Problem of Codeforces

Leetcode/Java/Linked List Cycle II.java
Easy java solution for "Linked List Cycle II".
Please merge this @Ayush7614 @Amit366 @ravikr126 
Fixes #1995 
Replace #1995  with the issue number which is fixed in this PR
=> Java-Solution Linked List Cycle II

Algorithms/JohnsonAlgorithm.cpp
Addition of Johnson Algorithm
**Name of the File** - JohnsonAlgorithm.cpp
**Destination Folder** - Daily-Coding-DS-ALGO-Practice/Algorithms/
Fixes #1871
=> Added JohnsonAlgorithm.cpp

Algorithms/LinkedList/circularll.java, Algorithms/LinkedList/doublyll.java, Algorithms/LinkedList/singlyll.java
operation in singly,doubly,circular llin java 
Fixes #1416 
Replace #1416  with the issue number which is fixed in this PR
code change
=> operation in singly,doubly,circular llin java for issue number #1416

Leetcode/C++/Best-time-to-buy-and-sell-stocks-III.cpp
I have added the problem Best Time to Buy and Sell Stocks - III (HARD) to the Leetcode/C++ folder.
I have done it in an efficient way using C++ and added comments where necessary. 
Link to the problem: https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/
Fixes #1825 
<br><br>
=> Added Problem Best Time to buy and sell stocks - III

Data Structures/Stack/Java/Stack_Using_LinkedList.java
Added Test Cases, problem statement and practice link for implementation of stack using linked list
Fixes #1930
=> Added test cases and problem statement

Leetcode/Java/Maximum Length of Repeated Subarray.java
Easy Java-Solution for "Maximum Length of Repeated Subarray" using DP. 
Fixes #1899 
Replace #1899  with the issue number which is fixed in this PR
=> Added Java-Solution Maximum Length of Repeated Subarray

Leetcode/C++/maximum_length_of_repeated_subarray.cpp
Added maximum length of repeated subarray in c++
Fixes #1899 
=> Added maximum length of repeated subarray.

Data Structures/Tree/BST.py
I have added the Python code for different operations of Binary Search tree.
Please review my code 
fixes #1983
=>  BST in python added

Data Structures/symmetric_logo.cpp
I have written solution of problem "Move all negative numbers at beginning"
Fixes #1976 
=> Solution for Roy and Symmetric Logos

Codechef/C++/Relativity (RELATIVE).cpp
Fixes #2007 
Problem name : Relativity
Problem Code : RELATIVE
Problem link : https://www.codechef.com/JULY21C/problems/RELATIVE
C++
=> Added "Relativity" problem of codechef July Long Challenge

Codechef/C++/Maximum Production (EITA).cpp
Fixes #2006 
Problem name : Maximum Production
Problem Code : EITA
Problem link : https://www.codechef.com/JULY21C/problems/EITA
C++
=> Added "Maximum Production" problem of codechef July Long Challenge

Atcoder dp/X - Tower.cpp
This is a C++ solution of the problem X - Tower from  very famous Atcoder Dp Series
Fixes #2146
=> X - Tower -file

Codeforces/C++/evenodd.cpp
=> ADDED SOLUTION TO PROBLEM 318A

Leetcode/Java/Swap Nodes in Pairs.java
Added easy java solution for "Swap Nodes in Pairs".
Fixes #1951 
Replace #1951 ` with the issue number which is fixed in this PR
=> Java-Solution Swap Nodes in Pairs

Leetcode/Java/BinaryTreeFromPreorderAndInorder.java
Constructed A Binary Tree from Preorder and Inorder Traversal in Java Language.
Fixes #1344 
=> Added Code for constructing binary tree from preorder and inorder in java Issue 1344

Gfg/Java/Merge_two_sorted_LL.java
- Added solution for merge two sorted linked list in Gfg/java folder.
Fixes #2140
=> Added Merge two sorted LL in Gfg/java folder

Gfg/Java/Find_Nth_Node_From_End_of_LL.java
- Added solution for Find Nth node from end of the Linked List in Gfg/java folder.
Fixes #2139
=> Find Nth Node from end of LL

Gfg/C++/count_the_triplets.cpp
Count the triplets in C++
Fixes #2147
=> Count the triplets

Gfg/merge_without_extra_space.java
merge without extra space in java
merge two sorted arrays in java without using extra space
Fixes #1817 
Replace #1817  with the issue number which is fixed in this PR
code change in java
=> merge request for issue #1817

Gfg/negitivenumber.java
move all negative number in beginning
Fixes #1766 
Replace #1766 with the issue number which is fixed in this PR
code change
=> merge request for 1766

Leetcode/C++/Kth smallest element in BST.cpp
=> added code for kth smallest element in bst

Leetcode/C++/Valid Anagrams.cpp
=> added code for Valide Anagrams

Leetcode/C++/SquareIsEqualToProduct.cpp
Number of Ways Where Square of Number Is Equal to Product of Two Numbers
The problem is taken from **LeetCode**.
**Problem Name** - Number of Ways Where Square of Number Is Equal to Product of Two Numbers
**Problem Link** - https://leetcode.com/problems/number-of-ways-where-square-of-number-is-equal-to-product-of-two-numbers/
**Statement** - Given two arrays of integers nums1 and nums2, return the number of triplets formed (type 1 and type 2) under the following rules:
Type 1: Triplet (i, j, k) if `nums1[i]2 == nums2[j] * nums2[k]` where `0 <= i < nums1.length and 0 <= j < k < nums2.length`.
Type 2: Triplet (i, j, k) if `nums2[i]2 == nums1[j] * nums1[k]` where `0 <= i < nums2.length and 0 <= j < k < nums1.length`.
**Name of the File** - SquareIsEqualToProduct.cpp
**Destination Folder** - …
=> Added SquareIsEqualToProduct.cpp

Algorithms/Searching and Sorting/C/sort_012_arr.c
Fixes #1768 
issue number 1768 is fixed in this PR.
Code is added in algorithms/searching and sorting/C folder.
Test cases also have been added.
=> Sorting an Array of 0s 1s and 2s

Codeforces/Help_Vasilisa_the_Wise_2.cpp
=> Help Vasilisa the Wise 2 on Codeforces #1472

Miscellaneous problems/arraysorting/sort_arr.c
solution code in C for sorting an array of 0s,1s and 2s is added in Miscellaneous Problems Folder
Fixes #1768 
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines(Clean Code) of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
=> Sol for sorting an array of 012 in C

Leetcode/C++/Clone graph.cpp
=> added code for clone graph

Gfg/Python/merge_two_sorted_array_without_extra_space.py
Added merge two sorted arrays without extra space in python.
Fixes #1817 
=> Added merge two sorted arrays without extra space.

Hackerank/C++/Cats and a Mouse.cpp
Code added for Cats and a Mouse problem in C++
Fixes #2167
=> Cats and a Mouse- HackerRank

Codechef/C++/XxOoRr (XXOORR).cpp
Fixes #2008 
Problem name : XxOoRr
Problem Code : XXOORR
Problem link : https://www.codechef.com/JULY21C/problems/XXOORR
C++
=> Added "XxOoRr" problem of codechef (July Long Challenge)

Codechef/C++/MINNOTES.cpp
Fixes #2009 
Problem name : Optimal Denomination
Problem Code : MINNOTES
Problem link : https://www.codechef.com/JULY21C/problems/MINNOTES
C++
=> Added "Optimal Denomination" problem of codechef (July Long Challenge)

Gfg/C++/Maximum_Index.cpp
Maximum Index Solution in C++
Fixes #2165
=> Maximum Index

Algorithms/Greedy Algorithms/0-1 KNAPSACK PROBLEM.c
Solve 0/1 Knapsack Problem using C.
Fixes #1455
=> 0/1 Knapsack Problem

Leetcode/C++/Total Hamming Distance.cpp
=> added code for total hamming distance

Leetcode/C++/Find the dupliacte number.cpp
=> added code for duplicate number

Gfg/Java/collinearity0fthreepoints.java
=> added issue#1616

Gfg/C++/minimum_sum.cpp
Code added for Minimum sum in C++
Fixes #2183
=> Minimum sum

Leetcode/C++/Find the longest substring containing vowels at even positions.cpp
=> added code for longest-substring-containing-vowels-in-even-counts

Gfg/C++/minimum_swap_sort.cpp
Given an array of n distinct elements. Find the minimum number of swaps required to sort the array in strictly increasing order.
Fixes #2116
=> minumum swap to sort

Leetcode/C++/Climbing stairs.cpp
=> added code for climbing stairs

Algorithms/Miscellaneous/C++/RatInMaze.cpp
**Rat In A Maze**
**Problem** - Rat In A Maze
**Statement** - You are given a 'N' * 'N' maze with a rat placed at 'MAZE[0][0]'. Find and print all paths that rat can follow to reach its destination i.e. 'MAZE['N' - 1]['N' - 1]'. Rat can move in any direc­tion ( left, right, up and down).
Value of every cell in the 'MAZE' can either be 0 or 1. Cells with value 0 are blocked means the rat can­not enter into those cells and those with value 1 are open.
**Name of the File** - RatInMaze.cpp
**Destination Folder** - Daily-Coding-DS-ALGO-Practice/Algorithms/Miscellaneous/C++/RatInMaze.cpp
This problem is done under **LGM-SOC'21** in **C++ Language**.
Fixes #2166
=> Added RatInMaze.cpp

Leetcode/C++/Invert binary tree.cpp
=> added code for invert binary tree

Gfg/Minimum spanning tree.cpp
=> added code for minimum spanning tree

Hackerank/Java/Larrys Array.java
Easy java solution for "Larrys Array".
Fixes #2118 
Replace #2118 with the issue number which is fixed in this PR
=> Java-Solution Larrys Array

Hackerank/C++/Variable Sized Arrays.cpp
The problem is a part of C++, HackerRank . It showcases how variable size arrays can be implemented using loops. Difficulty level of problem is easy.
Fixes #1159 
-  New feature (non-breaking change which adds functionality)
✔ My code follows the style guidelines(Clean Code) of this project
✔ I have performed a self-review of my own code
✔ I have commented my code, particularly in hard-to-understand areas
✔ I have created a helpful and easy to understand README.md
✔ My changes generate no new warnings
✔ I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
=> Create Variable Sized Arrays.cpp

Gfg/C/neg.c
Fixes #1766 
issue number 1766 is fixed in this PR
File containing Code to move all negative numbers at beginning has been added in the Gfg/C folder
=> Sol to shift neg nos at beg

Gfg/C/firstindex.c
Fixes #1689 
issue number 1689 is fixed in this PR
File for code in C to get the first index of number in array has been added in Gfg/C folder.
=> Sol for first index of no in array

Codechef/C++/Cricket Ranking (CRICRANK).cpp
Fixes #2215 
Problem name :Cricket Ranking
Problem Code : CRICRANK
Problem link : https://www.codechef.com/START6C/problems/CRICRANK
C++
=> Added "Cricket Ranking" problem of codechef

Codechef/C++/Three Dices (THREDICE).cpp
Fixes #2216 
Problem name :Three Dices
Problem Code : THREDICE
Problem link : https://www.codechef.com/START6C/problems/THREDICE
C++
=> Added "Three Dices" problem of codechef

Gfg/C++/top_View_of_Binary_Tree.cpp
Code added for Top View of Binary Tree in C++
Fixes #2208
=> Top View of Binary Tree

Hackerank/C++/Ice Cream Parlor.cpp
Code added for Ice Cream parlor problem in HackerRank
Fixes #2230
=> Ice Cream Parlor- HackerRank

Gfg/C++/Triangular_Number.cpp
Triangular Number Solution in C++
Fixes #2233
=> Triangular Number

Gfg/C++/Day_of_the_week.cpp
Day of the Solution in C++
Fixes #2237
=> Day of the week

Data Structures/gap_method.cpp
I added the code of Gap Method to sort array without using extra space. I explained all the parts of code .
Fixes #(780) : Gap Algorithm in C++ 
=> added code for the gap method

Gfg/C++/Handshakes.cpp
Handshakes problem solution in C++
Fixes #2239
=>  Handshakes

Miscellaneous problems/C/spiral_matrix.c
Print given matrix into Spiral form
Fixes #2240 
=> Print given matrix into Spiral form

Gfg/C++/Mirror tree.cpp
=> added code for mirror tree

Gfg/C++/BFS.cpp
=> Added code for bfs traversal 

Hackerank/C++/Camel Case.cpp
Added code for Camel Case problem in C++
Fixes #2247
=> Camel Case- HackerRank

Hackerank/C++/Jumping on the Clouds- Revisited.cpp
Code added for Jumping on the Clouds- Revisited problem in C++
Fixes #2259
=> Jumping on the Clouds- Revisited

Data Structures/Graph/C++/Bipartite_using_DFS.cpp
- Added Solution of Bipartite using DFS
- LGM-SOC'21
Fixes #2263  
=> Added Solution of Bipartite using DFS

Data Structures/Graph/C++/cycle_in_undirectedgraph_using_dfs.cpp
- Added Solution of Cycle in Undirected Graph using DFS.
- LGM-SOC'21
Fixes #2262 
=> Added Solution of Undirected Graph using DFS.

Hackerank/C++/Find Digits.cpp
Code added for Find Digits problem in C++
Fixes #2270
=> Find Digits- HackerRank

Gfg/C++/bridge_edge_in_graph.cpp
Fixes #2228 
Code added for Bridge Edge in Graph in C++
=> Bridge Edge in Graph

Hackerank/Java/Sparse Arrays.java
Java Solution for "Sparse Arrays" in 2-3 lines.
Fixes #2117 
Replace `2117` with the issue number which is fixed in this PR
=> Java-Solution sparse Arrays

Algorithms/superdigit.c
Calculate the Super digit of a number using a basic arithmetic algorithm.
Fixes #2242 
=> Calculate Super digit of a number using basic arithmetic algorithm

Gfg/Java/Delete_Loop_from_LL.java
Added solution for Delete Loop from linked list in Gfg/java folder.
Fixes #2138
=> Delete Loop from Linked List

Leetcode/Java/Excel Sheet Column Title.java
Java Solution for "Excel Sheet Column Title" using 'Array' and 'StringBuilder' in minimum lines.
Fixes #2193 
Replace `2193` with the issue number which is fixed in this PR
=> Java-Solution Excel Sheet Column Title

Leetcode/Java/Unique Paths.java
Java solution for "Unique Paths" using array in simplest form.
Fixes #2194 
Replace `2194` with the issue number which is fixed in this PR
=> Java-Solution Unique Paths

Hackerank/Java/Camel Case.java
Java solution for "Camel Case" in 3 line using for loop.
Fixes #2247 
Replace `2247` with the issue number which is fixed in this PR
=> Java-Solution Camel Case

Gfg/Python/rCircularLinked.py
Fixes #(https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/990#issuecomment-862674367)
=> fileuploaded

Hackerank/C++/Beautiful Days at the Movies.cpp
Code added for Beautiful days at the Movies in C++
Fixes #2279
=> Beautiful days at the Movies

Data Structures/constructing a bst.py
=> constructing bst using given keys

Leetcode/Python/maxrectangle.py
Fixes #(https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/2258#issuecomment-887851779)
=> Maxrectangle.py

Codechef/C++/Shoe Fit (SHOEFIT).cpp
Fixes #2283 
Problem name : Shoe Fit
Problem Code : SHOEFIT
Problem link : https://www.codechef.com/COOK131C/problems/SHOEFIT
C++
=> Added "Shoe Fit" problem of codechef

Codechef/C++/Ceiling Sum (CEILSUM).cpp
Fixes #2273 
Problem name : Ceiling Sum
Problem Code : CEILSUM
Problem link : https://www.codechef.com/START7C/problems/CEILSUM
C++
=> Added "Ceiling Sum" problem of codechef 

Leetcode/C++/01_Matrix.cpp
Code added for 0 1 Matrix in C++
Fixes #2271
=> 0 1 Matrix #2271

Hackerank/C++/Designer PDF Viewer.cpp
Code added for designer PDF viewer problem in C++
Fixes #2296
=> Designer PDF viewer- HackerRank

Leetcode/C++/Daily temperatures.cpp
=> Added code for daily temperatures

Hackerank/C++/Strong Password.cpp
Code added for Strong Password problem in C++
Fixes #2299
=> Strong password- HackerRank

Hackerank/C++/Mars Exploration.cpp
Code added for Mars Exploration problem in C++
Fixes #2300
=> Mars exploration- HackerRank

Leetcode/maximalrectangle.java
maximual rectangle leetcode in java
Fixes #2258 
Replace #2258  with the issue number which is fixed in this PR
code change
=> maximual rectangle leetcode in java

Leetcode/C++/Evaluate-reverse-polish-notation.cpp
=> added code for evaluate reverse polish notation

Codechef/C++/Food Chain (FODCHAIN).cpp
Fixes #2268 
Problem name : Food Chain
Problem Code : FODCHAIN
Problem link : https://www.codechef.com/START7C/problems/FODCHAIN
C++
=> Added "Food Chain" problem of codechef

Codechef/C++/XOR-ORED (XORORED).cpp
Fixes #2285 
Problem name : XOR-ORED
Problem Code : XORORED
Problem link : https://www.codechef.com/COOK131C/problems/XORORED
C++
=> Added "XOR-ORED" problem of codechef

Codechef/C++/Chef and Spells (CHFSPL).cpp
Fixes #2302 
Problem name : Chef and Spells
Problem Code : CHFSPL
Problem link : https://www.codechef.com/LTIME98C/problems/CHFSPL
C++
=> Added "Chef and Spells" problem of codechef

Codechef/C++/Chef In Infinite Plane (CHFPLN).cpp
Fixes #2286 
Problem name : Chef In Infinite Plane
Problem Code : CHFPLN
Problem link : https://www.codechef.com/COOK131C/problems/CHFPLN
C++
=> Added "Chef In Infinite Plane" problem of codechef

Codechef/C++/Red Alert (REDALERT).cpp
Fixes #2303 
Problem name : Red Alert
Problem Code : REDALERT
Problem link : https://www.codechef.com/LTIME98C/problems/REDALERT
C++
=> Added "Red Alert" problem of codechef

Codechef/C++/Beautiful Pairs (BUTYPAIR).cpp
Fixes #2305 
Problem name : Beautiful Pairs
Problem Code : BUTYPAIR
Problem link : https://www.codechef.com/LTIME98C/problems/BUTYPAIR
C++
=> Added "Beautiful Pairs" problem of codechef

Data Structures/Array/C++/SubArrayWithSum.cpp
**Finding Sub Array with Given Sum**
**Problem** - Finding Sub Array with Given Sum
**Statement** - Given an array and an integer k find the maximum sum of k consecutive elements.
**Name of the File** - SubArrayWithSum.cpp
**Destination Folder** - Daily-Coding-DS-ALGO-Practice/Data Structures/Array/C++/SubArrayWithSum.cpp
Fixes #2318 
This is under **LGM-SOC'21**
=> Added SubArrayWithSum.cpp

Hackerank/C++/Alternating Characters.cpp
Code added for Alternating Characters problem in C++
Fixes #2315
=> Alternate Characters- HackerRank

Leetcode/C++/Letter_Combinations_Phone_Number.cpp
Added the C++ solution for Letter Combinations of Phone Number under LGMSOC 21
Fixes #2335 
@Amit366 @ravikr126 @Ayush7614 
=> C++ Solution for "Letter Combinations of a Phone Number" under LGMSOC21

Codechef/Java/MaximumArrayXOR.java
Added Maximum Array XOR problem to Codechef folder from Codechef starters challenge.
Problem name: Maximum Array XOR problem
Problem code: MAXARXOR
Problem link: https://www.codechef.com/START7C/problems/MAXARXOR
Fixes #2245
Please review this issue and merge it.
=> Added Maximum Array XOR problem

Algorithms/Searching and Sorting/C++/Count Sort.cpp
Code added for Count Sort in C++ 
Fixes #2326
=> Count sort- Algorithms

Codechef/Java/Chess Format.java
Added Java solution for "chess format" of codechef LunchTime question.
Fixes #2268 
Replace `2268` with the issue number which is fixed in this PR
=> Java-Solution Chess Format

Codechef/Java/Food Chain.java
Added java solution for "Food Chain" form Codechef LunchTime question.
Fixes #2267 
Replace `2267` with the issue number which is fixed in this PR
=> Java-Solution Food Chain

Gfg/Java/SilverAndGold.java
Added Silver and Gold problem which was asked in GeeksforGeeks Job-A-Thon: For Internship Contest.
**Problem statement:**
There are N coins kept in a line. Each coin has two sides - one is colored gold and the other silver. You can flip two adjacent coins any number of times. You need to make the gold-colored side of every coin facing up. You are given the initial status of coins in a binary string s where 1 represents the gold side facing up and 0 represents the silver side facing up. If it is possible to make the gold-colored side of every coin facing up, return  Yes, otherwise return  No
**Input:**
N = 8, s = "11001100"
**Output**:
Yes
**Explanation:**
Flipping 3rd and 4th coin together and 7th
and 8th coin together will do the task.
**Input:**
N = 8, s = "10010100"
**Output:**
No …
=> Added Silver and Gold problem from gfg Job-A-Thon

Gfg/C++/Delete_without_head_pointer.cpp
Question:
You are given a pointer/ reference to the node which is to be deleted from the linked list of N nodes. The task is to delete the node. Pointer/ reference to head node is not given.
Note: No head reference is given to you. It is guaranteed that the node to be deleted is not a tail node in the linked list.
Fixes #([1648](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/1648))
=> Added code for issue 1648

Operating System/CPU Scheduler/banker algo.cpp
Banker algo for deadlock avoidance.
=> banker algo

Codechef/Java/racingHorses.java
=> Added solution of Racing Hosrses(CodeChef) in Java under LGMSOC'21

Codechef/Java/atm.java
=> Added Solution of  ATM(Codechef) in Java under LGMSOC'21

Codechef/Java/studyingAlphabet.java
=> Added Solution of studying Alphabet (Codechef) in Java Under LGMSOC'21

Codechef/C++/falseno.cpp, Codechef/C++/gcd.cpp, Codechef/C++/htmltags.cpp, Codechef/C++/infiniteplane.cpp, Codechef/C++/richirich.cpp, Codechef/Java/xor.java
=> Added Codes in the CodeChef folder

Algorithms/Hashing Techniques/Chaining.cpp
Code added for Chaining algorithm in Hashing
Fixes #2358
=> Chaining- Hashing

Leetcode/Python/reverseInteger.py
Added solution of Reverse Integer(Leetcode) in Python.
Fixes #1539 
=> Added solution of Reverse Integer(Leetcode) in Python.

Leetcode/Python/multiplyStrings.py
Added solution of Multiply Strings(Leetcode) in Python.
Fixes #1540 
=> Added solution of Multiply Strings(Leetcode) in Python Under LGMSoc'21

Leetcode/Java/createTargetArray.java
Added solution of create Target Array in Given Order (Leetcode) in Java. under LGMSOC'21
Fixes #1551 
=> Added solution of create Target Array in Given Order (Leetcode) in Java. under LGMSOC'21

Codechef/Java/The_Lead_Game.java
Added solution of The Lead Game (CodeChef) in Java
Fixes #1202 
=> Added Solution of The Lead Game(Codechef) in Java.

Gfg/DisplayNumberInWord.cpp
This program is written in C++ Language and convert a no in word format
Input:1234
Output:  One thousand two  hundred and thirty four
Fixes #2356
Replace #2356 with the issue number which is fixed in this PR
=> Code For Display The number In word Format

Gfg/Java/Sort_012s.java
Added solution for sort 0,1,2's
Fixes #2349
=> Sort an array containing only 0,1,2's

Leetcode/C++/Two Sum II - Input array is sorted.cpp
=> TWO sum - II problem added

Data Structures/Shortest Distance in Weighted graph using BFS
Create Shortest Distance in Weighted graph using BFS using Java
Fixes #(#2291)
=> Create Shortest Distance in Weighted graph using BFS

Data Structures/LinkedList/C++/Pallindrome_Linked_List.cpp
Signed-off-by: harsh6768-svg <1905391@kiit.ac.in>
Code to find whether a linked list is  pallindrome or not
Fixes #2380
Replace  #2380 with the issue number which is fixed in this PR
=> Added Pallindrome Code For Linked List

Codeforces/C/petya_and_strings.c
I have provided a solution for petya and strings problem in c language in the folder codeforces .
Fixes #2373
=> Solved issue no #2373 . (Codeforces)112A petya and string #2373  Petya and strings problem solution in c . 

Leetcode/C++/PartitionToKsubset.cpp
Signed-off-by: harsh6768-svg <1905391@kiit.ac.in>
This program is whenever we are having an array we have to devide it into k equal subsets and check the sum of that subset are equal through out the entire array.
Example 1:
Input: nums = [4,3,2,3,5,2,1], k = 4
Output: true
Explanation: It's possible to divide it into 4 subsets (5), (1, 4), (2,3), (2,3) with equal sums.
Example 2:
Input: nums = [1,2,3,4], k = 3
Output: false
Fixes #2404
Replace #2404 with the issue number which is fixed in this PR
=> Partition to K Equal Sum Subsets

Data Structures/Tree/C++/countNodes.cpp
=> Added count nodes

Leetcode/linked list component.cpp
Signed-off-by: Hrithik <1905394@gmail.com>
You are given the head of a linked list containing unique integer values and an integer array nums that is a subset of the linked list values.
Fixes #2411
Replace #2411 with the issue number which is fixed in this PR
=> Linked List Components

Data Structures/Tree/C++/countNodesgreaterthanX.cpp
Added count nodes greater than X.
Fixes #2425 
=> Added count Nodes greater than X

Gfg/C++/rotate matrix.cpp
=> Create rotate matrix.cpp

Gfg/Java/rotate matrix.java
=> Create rotate matrix.java

Data Structures/QueueUsingLL.cpp
=> QueueUsingLL

Leetcode/C++/Minimum Size Subarray Sum.cpp
Hey, I have given the solution of leetcode question **Minimum Size Subarray Sum** in c++.
Fixes #2412
=> Added Minimum Size Subarray Sum

Gfg/Java/second_largestnum.java
This will return the second largest number in the given array.
=> second_largest.java

Codeforces/Java/MajorityElement.java
Added the code for majority element in java
Fixes #(2468)
=> Majority Element

Leetcode/Python/AddTwoNumbers.py
ADDTWONUMBERS(medium):You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.
You may assume the two numbers do not contain any leading zero, except the number 0 itself.
Please allow me to contribute to these wonderful sets of problems. 
the solution is verified on leetcode itself.(included with necessary comments for the users to understand)
looking forward to contribute more.
=> AddTwoNumbers.py added

Leetcode/Java/SetZeroes.java
add solution for leetcode(medium) problem to set zeroes to all elements in a respective row and column where a zero is found.
-  [x] My code follows the style guidelines(Clean Code) of this project
-  [x] I have performed a self-review of my own code
-  [x] I have commented my code, particularly in hard-to-understand areas
-  [x] My changes generate no new warnings
=> add SetZeroes.java

Codechef/C++/FixedNumberOfFixedPoints.c++
https://www.codechef.com/START14B/problems/FIXFIX
=> FIXFIX Starters-14
